<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NLightning.Infrastructure.Bitcoin/NLightning.Infrastructure.Bitcoin.csproj"/>
  </ItemGroup>
</Project>
