namespace NLightning.Client.Utils;

public static class ClientUtils
{
    public static void ShowUsage()
    {
        Console.WriteLine("NLightning Node Client");
        Console.WriteLine("Usage:");
        Console.WriteLine("  nltg [options] [command]");
        Console.WriteLine();
        Console.WriteLine("Options:");
        Console.WriteLine("  --network, -n <network>    Network to use (mainnet, testnet, testnet4, regtest, signet, mutinynet) [default: mainnet]");
        Console.WriteLine("  --cookie, -c <path>        Path to cookie file");
        Console.WriteLine("  --help, -h, -?             Show this help message");
        Console.WriteLine();
        Console.WriteLine("Commands:");
        Console.WriteLine("  info                         Get node information via IPC");
        Console.WriteLine("  connect <node>               Connect to a peer node (pubkey@host:port; the host is an IP,");
        Console.WriteLine("                               a DNS name or a Tor v3 .onion, which needs Node:Tor)");
        Console.WriteLine("  listpeers                    List all connected peers");
        Console.WriteLine("  disconnect <node_id> [--force]");
        Console.WriteLine("                               Disconnect a peer (alias: disconnect-peer); refused while");
        Console.WriteLine("                               its channels have HTLCs in flight unless --force; the node");
        Console.WriteLine("                               does not reconnect it until the next connect or restart");
        Console.WriteLine("  shutdown [--wait [--timeout <seconds>]] [--force]");
        Console.WriteLine("                               Stop the node gracefully (alias: stop); refused while HTLCs");
        Console.WriteLine("                               are in flight; --wait drains until nothing is in flight (at");
        Console.WriteLine("                               most --timeout seconds [default: 300], Ctrl-C stops waiting),");
        Console.WriteLine("                               --force stops anyway (nothing is broadcast or force-closed,");
        Console.WriteLine("                               but the node must be back before the HTLC deadlines); while");
        Console.WriteLine("                               draining, new payments, channels and splices are refused;");
        Console.WriteLine("                               exits 0 when the node is stopping, 1 on a refusal or when");
        Console.WriteLine("                               the wait timed out");
        Console.WriteLine("  listchannels [peer_id]       List channels, optionally only those with one peer");
        Console.WriteLine("  getaddress [p2tr|p2wpkh|all] Gets an unused address of the requested type [default: p2tr]");
        Console.WriteLine("  walletbalance                Gets the wallet balance");
        Console.WriteLine("  withdraw <address> <amount_sat|all> [--sat-per-vb <n>]");
        Console.WriteLine("                               Send on-chain funds from the wallet (aliases: sendcoins,");
        Console.WriteLine("                               send-coins); all sends every confirmed output minus the");
        Console.WriteLine("                               fee and keeps the anchors reserve as change; fee rate");
        Console.WriteLine("                               1-1000 sat/vB [default: the node's estimate]");
        Console.WriteLine("  openchannel <node> <sats> [push_sats] [--public] [--dual-fund|--v1] [--no-wait]");
        Console.WriteLine("                               Open a channel to peer, optionally giving it push_sats;");
        Console.WriteLine("                               --public announces it once 6 blocks deep [default: private];");
        Console.WriteLine("                               dual-funded (open_channel2, the peer may add funds) when");
        Console.WriteLine("                               the peer supports option_dual_fund and no push_sats is");
        Console.WriteLine("                               given, v1 otherwise; --dual-fund requires v2, --v1 forces");
        Console.WriteLine("                               v1; prints the funding txid once published (and each");
        Console.WriteLine("                               bumpopen attempt), then waits for channel_ready unless");
        Console.WriteLine("                               --no-wait; Ctrl-C after the txid stops waiting, the open");
        Console.WriteLine("                               continues");
        Console.WriteLine("  createinvoice <msat|any> [description] [expiry_seconds]");
        Console.WriteLine("                               Create an invoice (alias: addinvoice)");
        Console.WriteLine("  payinvoice <bolt11> [msat] [timeout_seconds] [--max-fee-msat <msat>] [--max-parts <n>]");
        Console.WriteLine("             [--timeout <seconds>] [--out <channel>] [--in <channel>]");
        Console.WriteLine("                               Pay an invoice and wait for the outcome (alias: pay); the");
        Console.WriteLine("                               amount is only for invoices without one; exit code 1 if it");
        Console.WriteLine("                               failed; timeout 1-300 s [default: 60], also the end of the");
        Console.WriteLine("                               retries, then it stays in flight and listpayments shows the");
        Console.WriteLine("                               outcome; fee limit [default: max(0.5%, 5000 msat)]; parts:");
        Console.WriteLine("                               HTLCs in flight at once, 1-128, 1 never splits [default: 16];");
        Console.WriteLine("                               --out: the channel to leave through (channel id or scid); an");
        Console.WriteLine("                               invoice of our own is a rebalance over a circular route, --in");
        Console.WriteLine("                               the channel it comes back in through");
        Console.WriteLine("  payoffer <offer> [msat] [--quantity <n>] [--note <text>] [--max-fee-msat <msat>]");
        Console.WriteLine("           [--max-parts <n>] [--timeout <seconds>]");
        Console.WriteLine("                               Fetch an invoice for a BOLT 12 offer and pay it over its");
        Console.WriteLine("                               blinded paths (alias: pay-offer); the amount is only for");
        Console.WriteLine("                               offers without one (or in another currency); exit code 1");
        Console.WriteLine("                               if nothing was paid or the payment failed; the limits are");
        Console.WriteLine("                               those of payinvoice");
        Console.WriteLine("  keysend <node_id> <sats> [--tlv <type>=<hex>]... [--max-fee-msat <msat>]");
        Console.WriteLine("          [--timeout <seconds>]");
        Console.WriteLine("                               Send a spontaneous payment (no invoice) with our own");
        Console.WriteLine("                               preimage; --tlv adds a custom record for the payee (type");
        Console.WriteLine("                               65536 or more, repeatable); exit code 1 if it failed; the");
        Console.WriteLine("                               limits are those of payinvoice, never split");
        Console.WriteLine("  fetchinvoice <offer> [msat] [--quantity <n>] [--note <text>]");
        Console.WriteLine("                               Fetch and check an invoice for a BOLT 12 offer without");
        Console.WriteLine("                               paying it (alias: fetch-invoice)");
        Console.WriteLine("  closechannel <channel_id> [feerate_per_kw|0] [wait_seconds] [nofeerange]");
        Console.WriteLine("                               Cooperatively close a channel (alias: close-channel) and");
        Console.WriteLine("                               wait for the closing transaction [wait 0-300 s, default 30];");
        Console.WriteLine("                               nofeerange negotiates without fee_range");
        Console.WriteLine("  splicein <channel_id> <sats> [--feerate <sat_per_kw>]");
        Console.WriteLine("                               Splice wallet funds into a channel (alias: splice-in); the");
        Console.WriteLine("                               channel keeps working meanwhile; feerate 253-250000 sat/kw");
        Console.WriteLine("                               [default: the node's estimate]; exit code 1 if refused or");
        Console.WriteLine("                               aborted");
        Console.WriteLine("  spliceout <channel_id> <sats> [--address <address>] [--feerate <sat_per_kw>]");
        Console.WriteLine("                               Splice funds out of a channel to an address [default: a");
        Console.WriteLine("                               new address of the node's wallet] (alias: splice-out)");
        Console.WriteLine("  bumpsplice <channel_id> <feerate_per_kw> [--max-fee-sat <sats>]");
        Console.WriteLine("                               RBF the channel's pending splice at a higher feerate (alias:");
        Console.WriteLine("                               bump-splice); at least max(25/24 x, +25) of the latest");
        Console.WriteLine("                               attempt; --max-fee-sat caps our share of the new fee");
        Console.WriteLine("  bumpopen <channel_id> <feerate_per_kw> [--contribution-sat <sats>]");
        Console.WriteLine("                               RBF an unconfirmed dual-funded open (ours or the peer's) at");
        Console.WriteLine("                               a higher feerate (alias: bump-open); at least max(25/24 x,");
        Console.WriteLine("                               +25) of the latest attempt; --contribution-sat changes our");
        Console.WriteLine("                               contribution (0: the accepter stops contributing)");
        Console.WriteLine("  forceclosechannel <channel_id>");
        Console.WriteLine("                               Fail a channel and broadcast our latest commitment (alias:");
        Console.WriteLine("                               force-close-channel)");
        Console.WriteLine("  pendingsweeps [channel_id] [all]");
        Console.WriteLine("                               Show the on-chain resolution of closed channels (alias:");
        Console.WriteLine("                               pending-sweeps); all includes the closed ones");
        Console.WriteLine("  chainstatus                  Show whether chain processing is halted and what is refused");
        Console.WriteLine("                               meanwhile (alias: chain-status); exit code 1 if halted");
        Console.WriteLine("  listnodes [node_id]          List the announced nodes of the gossip graph (alias:");
        Console.WriteLine("                               list-nodes)");
        Console.WriteLine("  listgraphchannels [scid] [node_id]");
        Console.WriteLine("                               List the gossip graph's channels with both policies (alias:");
        Console.WriteLine("                               list-graph-channels); scid as BLOCKxTXxOUTPUT");
        Console.WriteLine("  getroute <node_id> <amount_msat> [--max-fee-msat <msat>] [--final-cltv <blocks>]");
        Console.WriteLine("                               Show the route a payment would take now, hop by hop, with");
        Console.WriteLine("                               fees, CLTVs and its success estimate (alias: get-route)");
        Console.WriteLine("  describegraph [--channels] [--nodes] [--limit <n>] [--offset <n>]");
        Console.WriteLine("                               Show the gossip graph's counts, memory, queues and sync");
        Console.WriteLine("                               peers (alias: describe-graph), with a page of channels");
        Console.WriteLine("                               and/or nodes [limit 1-1000, default 100]");
        Console.WriteLine("  exportchanbackup [channel_id] [--output <file>]");
        Console.WriteLine("                               Export the static channel backup, encrypted to the node");
        Console.WriteLine("                               key (alias: export-chan-backup); hex without --output");
        Console.WriteLine("  verifychanbackup <file> | verifychanbackup --hex <backup_hex>");
        Console.WriteLine("                               Check a channel backup against this node's key and chain");
        Console.WriteLine("                               (alias: verify-chan-backup); exit code 1 if invalid");
        Console.WriteLine("  restorechanbackup <file> | restorechanbackup --hex <backup_hex>");
        Console.WriteLine("                               After losing the channel database: ask each backed-up");
        Console.WriteLine("                               channel's peer to force close and sweep our funds");
        Console.WriteLine("                               (alias: restore-chan-backup); exit code 1 on a failure");
        Console.WriteLine("  listpeerstorage [node_id] [--blob]");
        Console.WriteLine("                               Show the backups our peers handed back (peer storage),");
        Console.WriteLine("                               with the channels they name that this node does not know,");
        Console.WriteLine("                               and the blobs we keep for peers (alias: list-peer-storage);");
        Console.WriteLine("                               --blob prints each handed-back blob as hex");
        Console.WriteLine("  setchannelpolicy <channel> [--fee-base-msat <n>] [--fee-ppm <n>] [--cltv-delta <n>]");
        Console.WriteLine("                   [--htlc-min-msat <n>] [--htlc-max-msat <n>] [--reset]");
        Console.WriteLine("                               Change one channel's routing policy now (alias:");
        Console.WriteLine("                               set-channel-policy): signed and sent as a new");
        Console.WriteLine("                               channel_update, enforced when forwarding; unset values");
        Console.WriteLine("                               keep Node:Routing, --reset goes back to it; <channel> is a");
        Console.WriteLine("                               channel id or a short channel id (BLOCKxTXxOUTPUT)");
        Console.WriteLine("  getchannelpolicy <channel>   Show one channel's routing policy in force (alias:");
        Console.WriteLine("                               get-channel-policy)");
        Console.WriteLine("  createoffer <msat|any> [description] [--issuer <text>] [--quantity-max <n>]");
        Console.WriteLine("              [--absolute-expiry <unix_seconds>] [--paths]");
        Console.WriteLine("                               Create a BOLT 12 offer (alias: create-offer); an amount");
        Console.WriteLine("                               needs a description; --quantity-max 0 is unlimited; --paths");
        Console.WriteLine("                               adds blinded paths even with a public channel");
        Console.WriteLine("  listoffers [--active] [count] [skip]");
        Console.WriteLine("                               List our offers with their invoices, newest first (alias:");
        Console.WriteLine("                               list-offers) [count 1-1000, default 100]");
        Console.WriteLine("  disableoffer <offer_id>      Stop answering an offer's invoice requests (alias:");
        Console.WriteLine("                               disable-offer); issued invoices stay payable");
        Console.WriteLine("  listinvoices [count] [skip]  List invoices, newest first [count 1-1000, default 100]");
        Console.WriteLine("  listpayments [count] [skip]  List outgoing payments, newest first [count 1-1000,");
        Console.WriteLine("                               default 100]");
        Console.WriteLine("  listforwards [count] [skip] [--since <time>] [--until <time>]");
        Console.WriteLine("             [--status pending|offered|fulfilled|failed] [--channel <channel>]");
        Console.WriteLine("                               List payments we forwarded, newest first, with the fee");
        Console.WriteLine("                               earned, the totals over the filtered set and the HTLCs");
        Console.WriteLine("                               refused before forwarding since start [count 1-1000,");
        Console.WriteLine("                               default 100; time is Unix seconds or an ISO date; channel");
        Console.WriteLine("                               is a channel id or short_channel_id] (alias:");
        Console.WriteLine("                               list-forwards)");
        Console.WriteLine("  listaccountingevents [--after <seq>] [--limit <n>] [--kind <kind>[,<kind>...]]");
        Console.WriteLine("                       [--channel <channel>] [--since <time>] [--until <time>]");
        Console.WriteLine("                               List the accounting feed's sealed events in ledger order");
        Console.WriteLine("                               after a sequence (alias: list-accounting-events): signed");
        Console.WriteLine("                               msat from our side, fee, channel, hash, outpoint, peer,");
        Console.WriteLine("                               finality and details; prints the --after of the next");
        Console.WriteLine("                               page [limit 1-1000, default 100; kind is a name such as");
        Console.WriteLine("                               InvoiceSettled or its number]");
        Console.WriteLine("  accountingsnapshot           Show the live balances by bucket: each channel, pending");
        Console.WriteLine("                               on-chain funds and the wallet (alias: accounting-snapshot)");
        Console.WriteLine("  accounting report <balance|income|channels|peers|fees|register> [options]");
        Console.WriteLine("                               Report from the books: balance [--at <time>]; income and");
        Console.WriteLine("                               fees [--since <time>] [--until <time>]; channels and peers");
        Console.WriteLine("                               (routing earned in/out, payments, rebalance cost, on-chain");
        Console.WriteLine("                               fees, yield) [--since] [--until] [--channel <channel>];");
        Console.WriteLine("                               register [--since] [--until] [--channel] [--account");
        Console.WriteLine("                               <account>] [--kind <kind>[,...]] [--after <seq>] [--limit");
        Console.WriteLine("                               <n>]; amounts in msat and sat");
        Console.WriteLine("  accounting report <balance|income|register|gains|unrealized|lots|unvalued|unclassified|risk>");
        Console.WriteLine("                   --book financial [--currency <code>] [--price <price>] [--by <month|");
        Console.WriteLine("                   quarter|year|total>] [options]");
        Console.WriteLine("                               Report from the financial book (Accounting:Profile=");
        Console.WriteLine("                               Financial): msat and fiat, realized gains, open lots,");
        Console.WriteLine("                               unrealized gains at a price, rows to review, and the");
        Console.WriteLine("                               risk-weighted capital");
        Console.WriteLine("  accounting export --format <hledger|beancount|csv> [--since <time>] [--until <time>]");
        Console.WriteLine("                   [--output <file>] [--book financial [--currency <code>]]");
        Console.WriteLine("                               Export the books (exact msat amounts) to standard output");
        Console.WriteLine("                               or a file written by this client");
        Console.WriteLine("  accounting reconcile         Compare the books with the node's live balances");
        Console.WriteLine("  accounting rebuild           Clear the books and project the whole feed again");
        Console.WriteLine("  accounting verify            Walk the feed's hash chain and report the first break");
        Console.WriteLine("                               and check every period close's digest and signature");
        Console.WriteLine("  accounting rebuild --book financial");
        Console.WriteLine("                               Rebuild the financial book from the last period close");
        Console.WriteLine("  accounting close <period> [--force]");
        Console.WriteLine("                               Close and sign a period of the financial book (YYYY-MM or");
        Console.WriteLine("                               YYYY-MM-DD..YYYY-MM-DD); refused with unvalued or");
        Console.WriteLine("                               unclassified rows unless --force");
        Console.WriteLine("  accounting close list        List the periods and their closes");
        Console.WriteLine("  accounting close show <period>");
        Console.WriteLine("                               Show a close: digest, signature, balances");
        Console.WriteLine("  accounting classify rule add --account <name> [--priority <n>] [--kind <kinds>]");
        Console.WriteLine("                   [--label <regex>] [--tag <key>[=<glob>]] [--counterparty <node id>]");
        Console.WriteLine("                   [--offer <offer id>] [--channel <channel id>] [--disabled]");
        Console.WriteLine("                   [--description <text>]");
        Console.WriteLine("                               Add a financial classification rule (first match wins,");
        Console.WriteLine("                               by priority then id)");
        Console.WriteLine("  accounting classify rule <list|remove <id>|enable <id>|disable <id>>");
        Console.WriteLine("  accounting classify rule test <event key> [match options]");
        Console.WriteLine("                               Show where an event goes and why (and whether a");
        Console.WriteLine("                               candidate rule given by match options matches it)");
        Console.WriteLine("  accounting classify set <event key> <account> [--note <text>] | unset <event key>");
        Console.WriteLine("                               Reclassify one event by hand (wins over the rules)");
        Console.WriteLine("  accounting classify list [--skip <n>] [--limit <n>]");
        Console.WriteLine("  accounting classify list --unclassified [--after <seq>] [--limit <n>]");
        Console.WriteLine("                               List the overrides, or the entries that go to an");
        Console.WriteLine("                               unclassified account");
        Console.WriteLine("  accounting prices import <file> [--currency <code>]");
        Console.WriteLine("                               Store prices from a unixSeconds,price file (bad lines listed)");
        Console.WriteLine("  accounting prices list [--since <time>] [--until <time>] [--limit <n>] [--currency <code>]");
        Console.WriteLine("                               The stored BTC prices, oldest first");
        Console.WriteLine("  accounting prices fetch --since <time> [--until <time>]");
        Console.WriteLine("                               Ask the price sources for every hour of the range (31 days max)");
        Console.WriteLine("  accounting lots import <file> [--currency <code>]");
        Console.WriteLine("                               Replace the opening balances' estimated cost basis with");
        Console.WriteLine("                               time,sats,cost lots (before the first close only)");
        Console.WriteLine();
        Console.WriteLine("Labels and tags (createinvoice, payinvoice, keysend, createoffer, payoffer, withdraw,");
        Console.WriteLine("openchannel):");
        Console.WriteLine("  [--label <text>] [--tag <key>=<value>]...");
        Console.WriteLine("                               Kept on the invoice, payment, offer, withdrawal or channel,");
        Console.WriteLine("                               shown by the list commands and copied into the accounting");
        Console.WriteLine("                               events; a label is at most 256 bytes, at most 16 tags, a");
        Console.WriteLine("                               key is 1-32 of a-z 0-9 _ . - and a value at most 128 bytes");
        Console.WriteLine();
        Console.WriteLine("Environment Variables:");
        Console.WriteLine("  NLTG_NETWORK               Network to use");
        Console.WriteLine("  NLTG_COOKIE                Path to cookie file");
        Console.WriteLine();
        Console.WriteLine("Cookie file location: ~/.nltg/{network}/nltg.cookie");
    }
}