using Microsoft.Extensions.Logging;

namespace NLightning.Application.Channels.Handlers;

using Domain.Channels.Commitments;
using Domain.Channels.Commitments.Interfaces;
using Domain.Channels.Enums;
using Domain.Channels.Models;
using Domain.Crypto.ValueObjects;
using Domain.Exceptions;
using Domain.Node.Options;
using Domain.Protocol.Interfaces;
using Domain.Protocol.Messages;
using Domain.Protocol.Models;
using Interfaces;
using Services;
using Taproot;

/// <summary>
/// Receives <c>revoke_and_ack</c> (BOLT 2, plan N6-T1): the engine checks that the secret generates the point of the
/// peer's revoked commitment (B2-RAA-R01, "MUST send an error and fail the channel") and rotates to the commitment we
/// signed last; the secret is inserted into the peer's shachain (B2-RAA-R02, R04), which is saved in the same save as
/// the transition (NL-136). The lock-in and irrevocable-removal events go to the HTLC switch. If changes are pending for
/// the peer, our next <c>commitment_signed</c> is sent.
/// </summary>
public class RevokeAndAckMessageHandler : IChannelMessageHandler<RevokeAndAckMessage>
{
    private readonly ILogger<RevokeAndAckMessageHandler> _logger;
    private readonly IRevocationVerifier _revocationVerifier;
    private readonly ChannelStateTransitionService _transitions;

    public RevokeAndAckMessageHandler(ILogger<RevokeAndAckMessageHandler> logger,
                                      IRevocationVerifier revocationVerifier,
                                      ChannelStateTransitionService transitions)
    {
        _logger = logger;
        _revocationVerifier = revocationVerifier;
        _transitions = transitions;
    }

    public async Task<IReadOnlyList<IChannelMessage>> HandleAsync(RevokeAndAckMessage message,
                                                                  ChannelState currentState,
                                                                  FeatureOptions negotiatedFeatures,
                                                                  CompactPubKey peerPubKey)
    {
        ArgumentNullException.ThrowIfNull(message);
        var payload = message.Payload;
        var channel = _transitions.GetUpdatableChannel(payload.ChannelId, currentState, "revoke_and_ack");
        var commitments = channel.Commitments!;
        var revokedNumber = commitments.RemoteCommit.Number;
        var secret = new Secret(payload.PerCommitmentSecret.ToArray());

        CommitmentsResult result;
        try
        {
            // A simple taproot channel's next_local_nonces replace the peer's verification nonces; the engine fails the
            // channel when they are absent or miss an active funding (NL-877 T3)
            var nonces = message.NextLocalNoncesTlv is { } noncesTlv
                             ? TaprootChannelNonces.ToDictionary(noncesTlv.Nonces)
                             : null;
            result = commitments.ReceiveRevoke(secret, payload.NextPerCommitmentPoint, _revocationVerifier, nonces);
        }
        catch (CommitmentViolationException e)
        {
            throw ChannelStateTransitionService.ToPeerException(e, payload.ChannelId);
        }

        // A fresh copy of the persisted shachain, so nothing changes in memory unless the save succeeds (I2)
        using var shachain = await _transitions.LoadRemoteShachainAsync(payload.ChannelId);
        if (!shachain.InsertSecret(secret, PerCommitmentIndex.From(revokedNumber)))
            throw new ChannelWarningException(
                $"[B2-RAA-R02] per_commitment_secret of commitment {revokedNumber} does not fit the peer's shachain",
                payload.ChannelId, "per_commitment_secret was not generated by the shachain")
            {
                CloseConnection = true
            };

        await _transitions.CommitAsync(channel, result, new ChannelStateExtras { RemoteShachain = shachain.Export() });

        if (_logger.IsEnabled(LogLevel.Debug))
            _logger.LogDebug("Peer revoked commitment {Number} of channel {ChannelId}", revokedNumber,
                             payload.ChannelId);

        var followUps = await SignFollowUpAsync(channel);
        return followUps.Count == 0 ? [] : [.. followUps];
    }

    /// <summary>
    /// Signs what is now pending for the peer: one commitment_signed, or with pending splices the whole batch
    /// (start_batch and one per active funding, SP-OP-03), in wire order. A failure is logged (the next trigger signs
    /// again).
    /// </summary>
    private async Task<IReadOnlyList<IChannelMessage>> SignFollowUpAsync(ChannelModel channel)
    {
        try
        {
            return await _transitions.SignPendingAsync(channel);
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Failed to sign the next remote commitment of channel {ChannelId}",
                             channel.ChannelId);
            return [];
        }
    }
}