<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.10"/>
    <PackageReference Include="MessagePack.Annotations" Version="3.1.10"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12"/>
  </ItemGroup>

</Project>
