<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.10"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NLightning.Daemon.Contracts\NLightning.Daemon.Contracts.csproj"/>
    <ProjectReference Include="..\NLightning.Domain\NLightning.Domain.csproj"/>
  </ItemGroup>

</Project>
