<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release;Debug.Native;Release.Native</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.0" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0" PrivateAssets="All" />
    <ProjectReference Include="../NLightning.Domain/NLightning.Domain.csproj" />
    <Protobuf Include="Protos/signer.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
