// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using NLightning.Domain.Channels.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Channel;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.SqlServer
{
    public static class InteractiveTxSessionEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref ChannelId ChannelId(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SessionId>k__BackingField")]
        public static extern ref Guid SessionId(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CommitmentSignedReceived>k__BackingField")]
        public static extern ref bool CommitmentSignedReceived(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CommitmentSignedSent>k__BackingField")]
        public static extern ref bool CommitmentSignedSent(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConstructedTx>k__BackingField")]
        public static extern ref byte[] ConstructedTx(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FeeratePerKw>k__BackingField")]
        public static extern ref uint FeeratePerKw(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Inputs>k__BackingField")]
        public static extern ref byte[] Inputs(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsInitiator>k__BackingField")]
        public static extern ref bool IsInitiator(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LocalContribution>k__BackingField")]
        public static extern ref byte[] LocalContribution(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LocalFundingSatoshis>k__BackingField")]
        public static extern ref long? LocalFundingSatoshis(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LocalReservationId>k__BackingField")]
        public static extern ref Guid? LocalReservationId(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Locktime>k__BackingField")]
        public static extern ref uint Locktime(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OurSharedInputSignature>k__BackingField")]
        public static extern ref byte[] OurSharedInputSignature(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OurWitnesses>k__BackingField")]
        public static extern ref byte[] OurWitnesses(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Outputs>k__BackingField")]
        public static extern ref byte[] Outputs(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Purpose>k__BackingField")]
        public static extern ref byte Purpose(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ResolvedAt>k__BackingField")]
        public static extern ref DateTimeOffset? ResolvedAt(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<State>k__BackingField")]
        public static extern ref byte State(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TheirCommitmentPartialSignature>k__BackingField")]
        public static extern ref byte[] TheirCommitmentPartialSignature(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TheirCommitmentSignature>k__BackingField")]
        public static extern ref byte[] TheirCommitmentSignature(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TheirSharedInputSignature>k__BackingField")]
        public static extern ref byte[] TheirSharedInputSignature(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TheirWitnesses>k__BackingField")]
        public static extern ref byte[] TheirWitnesses(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TxSignaturesReceived>k__BackingField")]
        public static extern ref bool TxSignaturesReceived(InteractiveTxSessionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TxSignaturesSent>k__BackingField")]
        public static extern ref bool TxSignaturesSent(InteractiveTxSessionEntity @this);
    }
}