// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using NLightning.Domain.Channels.ValueObjects;
using NLightning.Domain.Crypto.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Payment;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.SqlServer
{
    public static class PaymentHopEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PaymentHash>k__BackingField")]
        public static extern ref Hash PaymentHash(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HopIndex>k__BackingField")]
        public static extern ref byte HopIndex(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AmountMsat>k__BackingField")]
        public static extern ref long AmountMsat(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CltvExpiry>k__BackingField")]
        public static extern ref uint CltvExpiry(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HoldTimeMs>k__BackingField")]
        public static extern ref long? HoldTimeMs(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NodeId>k__BackingField")]
        public static extern ref CompactPubKey NodeId(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SharedSecret>k__BackingField")]
        public static extern ref byte[] SharedSecret(PaymentHopEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ShortChannelId>k__BackingField")]
        public static extern ref ShortChannelId ShortChannelId(PaymentHopEntity @this);
    }
}
