namespace NLightning.Domain.Crypto.Models;

using ValueObjects;

/// <summary>
/// A nonce generated by BIP 327 NonceGen: the secret part, which never leaves its signer and signs once, and the public
/// part sent to the other signers.
/// </summary>
public sealed record MusigNoncePair(MusigSecretNonce SecretNonce, MusigPublicNonce PublicNonce);