using System.Net;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Extensions.Logging;

namespace NLightning.LndGrpc.Tls;

/// <summary>
/// The server certificate in the data directory, as LND makes it (<c>lnd/cert</c>): <c>tls.cert</c> and
/// <c>tls.key</c>, an ECDSA P-256 self-signed CA certificate (key usages digital signature, key encipherment and
/// certificate signing, server authentication) for <c>localhost</c>, the host name, <c>127.0.0.1</c>, <c>::1</c>, the
/// listen address and the configured extra names and addresses, valid 14 months. Clients pin it. Generated when either
/// file is missing (the key written 0600 first, exclusively); an existing pair is used as it is, never replaced (delete
/// both to regenerate, e.g. after adding a name).
/// </summary>
public static class LndTlsFiles
{
    public const string CertificateFileName = "tls.cert";
    public const string KeyFileName = "tls.key";

    /// <summary>The certificate with its private key, generating the pair when missing.</summary>
    public static X509Certificate2 EnsureCreated(string directory, LndGrpcOptions options, TimeProvider timeProvider,
                                                 ILogger? logger = null)
    {
        Directory.CreateDirectory(directory);
        var certificatePath = Path.Combine(directory, CertificateFileName);
        var keyPath = Path.Combine(directory, KeyFileName);
        if (!File.Exists(certificatePath) || !File.Exists(keyPath))
        {
            if (File.Exists(certificatePath))
                File.Delete(certificatePath);
            if (File.Exists(keyPath))
                File.Delete(keyPath);

            Generate(certificatePath, keyPath, options, timeProvider.GetUtcNow());
            logger?.LogInformation("Generated the LND gRPC TLS certificate {Path}", certificatePath);
        }

        var certificate = X509Certificate2.CreateFromPemFile(certificatePath, keyPath);
        if (!OperatingSystem.IsWindows())
            return certificate;

        // SChannel cannot use an ephemeral key: round-trip through PKCS#12
        using (certificate)
            return X509CertificateLoader.LoadPkcs12(certificate.Export(X509ContentType.Pkcs12), null);
    }

    private static void Generate(string certificatePath, string keyPath, LndGrpcOptions options, DateTimeOffset now)
    {
        using var key = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var host = Dns.GetHostName();
        var request = new CertificateRequest(new X500DistinguishedName($"O=lnd autogenerated cert, CN={host}"), key,
                                             HashAlgorithmName.SHA256);
        request.CertificateExtensions.Add(new X509BasicConstraintsExtension(true, false, 0, true));
        request.CertificateExtensions.Add(new X509KeyUsageExtension(
                                              X509KeyUsageFlags.DigitalSignature
                                            | X509KeyUsageFlags.KeyEncipherment
                                            | X509KeyUsageFlags.KeyCertSign, true));
        request.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(
                                              [new Oid("1.3.6.1.5.5.7.3.1")], false));

        var names = new SubjectAlternativeNameBuilder();
        foreach (var name in new[] { "localhost", host }.Concat(options.TlsExtraDomains)
                                                        .Where(n => !string.IsNullOrWhiteSpace(n))
                                                        .Distinct(StringComparer.OrdinalIgnoreCase))
            names.AddDnsName(name);

        var addresses = new List<IPAddress> { IPAddress.Loopback, IPAddress.IPv6Loopback };
        if (IPAddress.TryParse(options.ListenAddress, out var listen)
         && !listen.Equals(IPAddress.Any) && !listen.Equals(IPAddress.IPv6Any))
            addresses.Add(listen);
        addresses.AddRange(options.TlsExtraIps.Select(IPAddress.Parse));
        foreach (var address in addresses.Distinct())
            names.AddIpAddress(address);
        request.CertificateExtensions.Add(names.Build());

        using var certificate = request.CreateSelfSigned(now.AddHours(-1), now.AddMonths(14));
        Macaroons.LndMacaroonFiles.WriteExclusive(keyPath, System.Text.Encoding.ASCII.GetBytes(key.ExportECPrivateKeyPem()));
        Macaroons.LndMacaroonFiles.WriteExclusive(certificatePath,
                                                  System.Text.Encoding.ASCII.GetBytes(certificate.ExportCertificatePem()));
    }
}