using System.Net;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using NLightning.Testing.Lnd;

namespace NLightning.Integration.Tests.Fixtures.Lnd;

public class DockerLndBackendTests
{
    [Fact]
    public async Task Given_ABackendNotStarted_When_ItsMembersAreRead_Then_TheySayItIsNotRunning()
    {
        // Arrange: no Docker call before StartAsync, and a backend that never started removes no container
        await using var backend = new DockerLndBackend();

        // Act & Assert
        Assert.Equal(TestBackendKind.Docker, backend.Kind);
        Assert.Throws<InvalidOperationException>(() => backend.Bitcoin);
        Assert.Throws<InvalidOperationException>(() => backend.BitcoinZmqPorts);
        Assert.Throws<InvalidOperationException>(() => backend.LndNodes);
        Assert.Throws<InvalidOperationException>(() => backend.GetLndNode("alice"));
        await Assert.ThrowsAsync<InvalidOperationException>(() => backend.RestartLndAsync("alice"));
    }

    [Fact]
    public void Given_NoHostAddressVariable_When_PeersDialUs_Then_TheyUseDockersHostName()
    {
        // Arrange
        var backend = new DockerLndBackend();

        // Act
        var host = backend.HostAddressForPeers;

        // Assert: HOST_ADDRESS when set (as before the backend split), else host.docker.internal
        Assert.Equal(Environment.GetEnvironmentVariable("HOST_ADDRESS") is { Length: > 0 } configured
                         ? configured
                         : "host.docker.internal", host);
    }

    [Fact]
    public async Task Given_AnLndConnection_When_OurNodeDialsIt_Then_ItUsesTheContainerIpAndThePeerPort()
    {
        // Arrange: the gRPC endpoint LNUnit hands out (the container's address and gRPC port); no call is made
        var backend = new DockerLndBackend();
        using var connection = LndNodeConnection.CreateWithoutNodeInfo(
            LndSettings.FromBytes("https://127.0.0.1:10009", CreatePemCertificate(), [0x02]));

        // Act
        var endpoint = await backend.GetLndPeerEndpointAsync(connection, TestContext.Current.CancellationToken);

        // Assert: the resolved IP (Docker keeps a restarted container's address, NL-262) and LND's p2p port
        Assert.Equal("127.0.0.1:9735", endpoint);
    }

    private static byte[] CreatePemCertificate()
    {
        using var key = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var request = new CertificateRequest("O=lnd, CN=lnd autogenerated cert", key, HashAlgorithmName.SHA256);
        var san = new SubjectAlternativeNameBuilder();
        san.AddIpAddress(IPAddress.Loopback);
        request.CertificateExtensions.Add(san.Build());
        using var certificate = request.CreateSelfSigned(DateTimeOffset.UtcNow.AddDays(-1),
                                                         DateTimeOffset.UtcNow.AddDays(30));
        return System.Text.Encoding.ASCII.GetBytes(certificate.ExportCertificatePem() + "\n");
    }
}