// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Json.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Domain.Bitcoin.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Cashu;
using NLightning.Infrastructure.Persistence.ValueConverters;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Sqlite
{
    [EntityFrameworkInternal]
    public partial class CashuDepositEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Cashu.CashuDepositEntity",
                typeof(CashuDepositEntity),
                baseEntityType,
                propertyCount: 6,
                unnamedIndexCount: 2,
                keyCount: 1);

            var txId = runtimeEntityType.AddProperty(
                "TxId",
                typeof(TxId),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("TxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<TxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TxIdConverter());
            txId.SetGetter(
                TxId (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.TxId(instance),
                bool (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.TxId(instance).Equals(default(TxId)));
            txId.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, TxId value) =>
                {
                    CashuDepositEntityUnsafeAccessors.TxId(instance) = value;
                    return instance;
                });
            txId.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, TxId value) =>
                {
                    CashuDepositEntityUnsafeAccessors.TxId(instance) = value;
                    return instance;
                });
            txId.SetAccessors(
                TxId (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.TxId(((CashuDepositEntity)(entry.Entity))),
                TxId (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.TxId(((CashuDepositEntity)(entry.Entity))),
                TxId (IInternalEntry entry) => entry.ReadOriginalValue<TxId>(txId, 0),
                TxId (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<TxId>(txId, 0));
            txId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            txId.TypeMapping = SqliteByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<TxId>(
                    bool (TxId v1, TxId v2) => v1.Equals(v2),
                    int (TxId v) => ((object)v).GetHashCode(),
                    TxId (TxId v) => v),
                keyComparer: new ValueComparer<TxId>(
                    bool (TxId v1, TxId v2) => v1.Equals(v2),
                    int (TxId v) => ((object)v).GetHashCode(),
                    TxId (TxId v) => v),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                converter: new ValueConverter<TxId, byte[]>(
                    byte[] (TxId txId) => ((byte[])txId),
                    TxId (byte[] bytes) => new TxId(bytes)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<TxId, byte[]>(
                    SqliteJsonByteArrayReaderWriter.Instance,
                    new ValueConverter<TxId, byte[]>(
                        byte[] (TxId txId) => ((byte[])txId),
                        TxId (byte[] bytes) => new TxId(bytes))));
            txId.SetCurrentValueComparer(new StructuralEntryCurrentProviderValueComparer(txId));
            txId.SetSentinelFromProviderValue(null);

            var outputIndex = runtimeEntityType.AddProperty(
                "OutputIndex",
                typeof(uint),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("OutputIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<OutputIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0u);
            outputIndex.SetGetter(
                uint (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.OutputIndex(instance),
                bool (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.OutputIndex(instance) == 0U);
            outputIndex.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, uint value) =>
                {
                    CashuDepositEntityUnsafeAccessors.OutputIndex(instance) = value;
                    return instance;
                });
            outputIndex.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, uint value) =>
                {
                    CashuDepositEntityUnsafeAccessors.OutputIndex(instance) = value;
                    return instance;
                });
            outputIndex.SetAccessors(
                uint (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.OutputIndex(((CashuDepositEntity)(entry.Entity))),
                uint (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.OutputIndex(((CashuDepositEntity)(entry.Entity))),
                uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(outputIndex, 1),
                uint (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<uint>(outputIndex, 1));
            outputIndex.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            outputIndex.TypeMapping = UIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            outputIndex.SetCurrentValueComparer(new EntryCurrentValueComparer<uint>(outputIndex));

            var amountSat = runtimeEntityType.AddProperty(
                "AmountSat",
                typeof(long),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("AmountSat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<AmountSat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            amountSat.SetGetter(
                long (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.AmountSat(instance),
                bool (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.AmountSat(instance) == 0L);
            amountSat.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, long value) =>
                {
                    CashuDepositEntityUnsafeAccessors.AmountSat(instance) = value;
                    return instance;
                });
            amountSat.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, long value) =>
                {
                    CashuDepositEntityUnsafeAccessors.AmountSat(instance) = value;
                    return instance;
                });
            amountSat.SetAccessors(
                long (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.AmountSat(((CashuDepositEntity)(entry.Entity))),
                long (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.AmountSat(((CashuDepositEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(amountSat, 2),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(amountSat));
            amountSat.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            amountSat.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var blockHeight = runtimeEntityType.AddProperty(
                "BlockHeight",
                typeof(uint),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("BlockHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<BlockHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);
            blockHeight.SetGetter(
                uint (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.BlockHeight(instance),
                bool (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.BlockHeight(instance) == 0U);
            blockHeight.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, uint value) =>
                {
                    CashuDepositEntityUnsafeAccessors.BlockHeight(instance) = value;
                    return instance;
                });
            blockHeight.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, uint value) =>
                {
                    CashuDepositEntityUnsafeAccessors.BlockHeight(instance) = value;
                    return instance;
                });
            blockHeight.SetAccessors(
                uint (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.BlockHeight(((CashuDepositEntity)(entry.Entity))),
                uint (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.BlockHeight(((CashuDepositEntity)(entry.Entity))),
                uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(blockHeight, 3),
                uint (IInternalEntry entry) => entry.GetCurrentValue<uint>(blockHeight));
            blockHeight.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            blockHeight.TypeMapping = UIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var quoteId = runtimeEntityType.AddProperty(
                "QuoteId",
                typeof(string),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("QuoteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<QuoteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            quoteId.SetGetter(
                string (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.QuoteId(instance),
                bool (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.QuoteId(instance) == null);
            quoteId.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, string value) =>
                {
                    CashuDepositEntityUnsafeAccessors.QuoteId(instance) = value;
                    return instance;
                });
            quoteId.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, string value) =>
                {
                    CashuDepositEntityUnsafeAccessors.QuoteId(instance) = value;
                    return instance;
                });
            quoteId.SetAccessors(
                string (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.QuoteId(((CashuDepositEntity)(entry.Entity))),
                string (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.QuoteId(((CashuDepositEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(quoteId, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(quoteId));
            quoteId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            quoteId.TypeMapping = SqliteStringTypeMapping.Default;

            var reportedAt = runtimeEntityType.AddProperty(
                "ReportedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(CashuDepositEntity).GetProperty("ReportedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CashuDepositEntity).GetField("<ReportedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new UtcTicksConverter());
            reportedAt.SetGetter(
                DateTimeOffset? (CashuDepositEntity instance) => CashuDepositEntityUnsafeAccessors.ReportedAt(instance),
                bool (CashuDepositEntity instance) => !(CashuDepositEntityUnsafeAccessors.ReportedAt(instance).HasValue));
            reportedAt.SetSetter(
                CashuDepositEntity (CashuDepositEntity instance, DateTimeOffset? value) =>
                {
                    CashuDepositEntityUnsafeAccessors.ReportedAt(instance) = value;
                    return instance;
                });
            reportedAt.SetMaterializationSetter(
                CashuDepositEntity (CashuDepositEntity instance, DateTimeOffset? value) =>
                {
                    CashuDepositEntityUnsafeAccessors.ReportedAt(instance) = value;
                    return instance;
                });
            reportedAt.SetAccessors(
                DateTimeOffset? (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.ReportedAt(((CashuDepositEntity)(entry.Entity))),
                DateTimeOffset? (IInternalEntry entry) => CashuDepositEntityUnsafeAccessors.ReportedAt(((CashuDepositEntity)(entry.Entity))),
                DateTimeOffset? (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset?>(reportedAt, 5),
                DateTimeOffset? (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset?>(reportedAt));
            reportedAt.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            reportedAt.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                keyComparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<DateTimeOffset, long>(
                    long (DateTimeOffset value) => value.UtcTicks,
                    DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<DateTimeOffset, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<DateTimeOffset, long>(
                        long (DateTimeOffset value) => value.UtcTicks,
                        DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero))));
            reportedAt.SetComparer(new NullableValueComparer<DateTimeOffset>(reportedAt.TypeMapping.Comparer));
            reportedAt.SetKeyComparer(new NullableValueComparer<DateTimeOffset>(reportedAt.TypeMapping.KeyComparer));

            var key = runtimeEntityType.AddKey(
                new[] { txId, outputIndex });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { quoteId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { reportedAt });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var txId = runtimeEntityType.FindProperty("TxId");
            var outputIndex = runtimeEntityType.FindProperty("OutputIndex");
            var amountSat = runtimeEntityType.FindProperty("AmountSat");
            var blockHeight = runtimeEntityType.FindProperty("BlockHeight");
            var quoteId = runtimeEntityType.FindProperty("QuoteId");
            var reportedAt = runtimeEntityType.FindProperty("ReportedAt");
            var key = runtimeEntityType.FindKey(new[] { txId, outputIndex });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((CashuDepositEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<TxId, uint, long, uint, string, DateTimeOffset?>(((ValueComparer<TxId>)(((IProperty)txId).GetValueComparer())).Snapshot(source.GetCurrentValue<TxId>(txId)), ((ValueComparer<uint>)(((IProperty)outputIndex).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(outputIndex)), ((ValueComparer<long>)(((IProperty)amountSat).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(amountSat)), ((ValueComparer<uint>)(((IProperty)blockHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(blockHeight)), (source.GetCurrentValue<string>(quoteId) == null ? null : ((ValueComparer<string>)(((IProperty)quoteId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(quoteId))), (source.GetCurrentValue<DateTimeOffset?>(reportedAt) == null ? null : ((ValueComparer<DateTimeOffset?>)(((IProperty)reportedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset?>(reportedAt))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((CashuDepositEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<TxId, uint>(((ValueComparer<TxId>)(((IProperty)txId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<TxId>(txId)), ((ValueComparer<uint>)(((IProperty)outputIndex).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<uint>(outputIndex)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CashuDeposits");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
