// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using NLightning.Domain.Channels.ValueObjects;
using NLightning.Domain.Crypto.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Payment;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Sqlite
{
    public static class PaymentEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PaymentHash>k__BackingField")]
        public static extern ref Hash PaymentHash(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AmountMsat>k__BackingField")]
        public static extern ref long AmountMsat(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bolt11>k__BackingField")]
        public static extern ref string Bolt11(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bolt12InvoiceBytes>k__BackingField")]
        public static extern ref byte[] Bolt12InvoiceBytes(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedAt>k__BackingField")]
        public static extern ref DateTimeOffset? CompletedAt(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CustomRecords>k__BackingField")]
        public static extern ref byte[] CustomRecords(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FailureCode>k__BackingField")]
        public static extern ref ushort? FailureCode(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FailureReason>k__BackingField")]
        public static extern ref string FailureReason(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FailureSourceIndex>k__BackingField")]
        public static extern ref int? FailureSourceIndex(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FeeMsat>k__BackingField")]
        public static extern ref long FeeMsat(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<InvoiceRequestMetadata>k__BackingField")]
        public static extern ref byte[] InvoiceRequestMetadata(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsTrampolineRelay>k__BackingField")]
        public static extern ref bool IsTrampolineRelay(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Label>k__BackingField")]
        public static extern ref string Label(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OfferBolt12>k__BackingField")]
        public static extern ref string OfferBolt12(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OutgoingChannelId>k__BackingField")]
        public static extern ref ChannelId? OutgoingChannelId(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OutgoingHtlcId>k__BackingField")]
        public static extern ref ulong? OutgoingHtlcId(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayeeNodeId>k__BackingField")]
        public static extern ref CompactPubKey PayeeNodeId(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayerNote>k__BackingField")]
        public static extern ref string PayerNote(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PaymentIndex>k__BackingField")]
        public static extern ref long? PaymentIndex(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Preimage>k__BackingField")]
        public static extern ref byte[] Preimage(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref byte Status(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tags>k__BackingField")]
        public static extern ref string Tags(PaymentEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Hops>k__BackingField")]
        public static extern ref ICollection<PaymentHopEntity> Hops(PaymentEntity @this);
    }
}
