// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Json.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Domain.Crypto.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Node;
using NLightning.Infrastructure.Persistence.ValueConverters;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Sqlite
{
    [EntityFrameworkInternal]
    public partial class PeerStorageRetrievalEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Node.PeerStorageRetrievalEntity",
                typeof(PeerStorageRetrievalEntity),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var nodeId = runtimeEntityType.AddProperty(
                "NodeId",
                typeof(CompactPubKey),
                propertyInfo: typeof(PeerStorageRetrievalEntity).GetProperty("NodeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PeerStorageRetrievalEntity).GetField("<NodeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new CompactPubKeyConverter());
            nodeId.SetGetter(
                CompactPubKey (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.NodeId(instance),
                bool (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.NodeId(instance).Equals(default(CompactPubKey)));
            nodeId.SetSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, CompactPubKey value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.NodeId(instance) = value;
                    return instance;
                });
            nodeId.SetMaterializationSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, CompactPubKey value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.NodeId(instance) = value;
                    return instance;
                });
            nodeId.SetAccessors(
                CompactPubKey (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.NodeId(((PeerStorageRetrievalEntity)(entry.Entity))),
                CompactPubKey (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.NodeId(((PeerStorageRetrievalEntity)(entry.Entity))),
                CompactPubKey (IInternalEntry entry) => entry.ReadOriginalValue<CompactPubKey>(nodeId, 0),
                CompactPubKey (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<CompactPubKey>(nodeId, 0));
            nodeId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            nodeId.TypeMapping = SqliteByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<CompactPubKey>(
                    bool (CompactPubKey v1, CompactPubKey v2) => v1.Equals(v2),
                    int (CompactPubKey v) => ((object)v).GetHashCode(),
                    CompactPubKey (CompactPubKey v) => v),
                keyComparer: new ValueComparer<CompactPubKey>(
                    bool (CompactPubKey v1, CompactPubKey v2) => v1.Equals(v2),
                    int (CompactPubKey v) => ((object)v).GetHashCode(),
                    CompactPubKey (CompactPubKey v) => v),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                converter: new ValueConverter<CompactPubKey, byte[]>(
                    byte[] (CompactPubKey compactPubKey) => ((byte[])compactPubKey),
                    CompactPubKey (byte[] bytes) => new CompactPubKey(bytes)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<CompactPubKey, byte[]>(
                    SqliteJsonByteArrayReaderWriter.Instance,
                    new ValueConverter<CompactPubKey, byte[]>(
                        byte[] (CompactPubKey compactPubKey) => ((byte[])compactPubKey),
                        CompactPubKey (byte[] bytes) => new CompactPubKey(bytes))));
            nodeId.SetCurrentValueComparer(new StructuralEntryCurrentProviderValueComparer(nodeId));
            nodeId.SetSentinelFromProviderValue(null);

            var blob = runtimeEntityType.AddProperty(
                "Blob",
                typeof(byte[]),
                propertyInfo: typeof(PeerStorageRetrievalEntity).GetProperty("Blob", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PeerStorageRetrievalEntity).GetField("<Blob>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            blob.SetGetter(
                byte[] (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.Blob(instance),
                bool (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.Blob(instance) == null);
            blob.SetSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, byte[] value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.Blob(instance) = value;
                    return instance;
                });
            blob.SetMaterializationSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, byte[] value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.Blob(instance) = value;
                    return instance;
                });
            blob.SetAccessors(
                byte[] (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.Blob(((PeerStorageRetrievalEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.Blob(((PeerStorageRetrievalEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(blob, 1),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(blob));
            blob.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            blob.TypeMapping = SqliteByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()));

            var matchesLastSent = runtimeEntityType.AddProperty(
                "MatchesLastSent",
                typeof(bool?),
                propertyInfo: typeof(PeerStorageRetrievalEntity).GetProperty("MatchesLastSent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PeerStorageRetrievalEntity).GetField("<MatchesLastSent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            matchesLastSent.SetGetter(
                bool? (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(instance),
                bool (PeerStorageRetrievalEntity instance) => !(PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(instance).HasValue));
            matchesLastSent.SetSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, bool? value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(instance) = value;
                    return instance;
                });
            matchesLastSent.SetMaterializationSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, bool? value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(instance) = value;
                    return instance;
                });
            matchesLastSent.SetAccessors(
                bool? (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(((PeerStorageRetrievalEntity)(entry.Entity))),
                bool? (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.MatchesLastSent(((PeerStorageRetrievalEntity)(entry.Entity))),
                bool? (IInternalEntry entry) => entry.ReadOriginalValue<bool?>(matchesLastSent, 2),
                bool? (IInternalEntry entry) => entry.GetCurrentValue<bool?>(matchesLastSent));
            matchesLastSent.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            matchesLastSent.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            matchesLastSent.SetComparer(new NullableValueComparer<bool>(matchesLastSent.TypeMapping.Comparer));
            matchesLastSent.SetKeyComparer(new NullableValueComparer<bool>(matchesLastSent.TypeMapping.KeyComparer));

            var receivedAt = runtimeEntityType.AddProperty(
                "ReceivedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(PeerStorageRetrievalEntity).GetProperty("ReceivedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PeerStorageRetrievalEntity).GetField("<ReceivedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksConverter());
            receivedAt.SetGetter(
                DateTimeOffset (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(instance),
                bool (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(instance).EqualsExact(default(DateTimeOffset)));
            receivedAt.SetSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, DateTimeOffset value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(instance) = value;
                    return instance;
                });
            receivedAt.SetMaterializationSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, DateTimeOffset value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(instance) = value;
                    return instance;
                });
            receivedAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(((PeerStorageRetrievalEntity)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.ReceivedAt(((PeerStorageRetrievalEntity)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(receivedAt, 3),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(receivedAt));
            receivedAt.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            receivedAt.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                keyComparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<DateTimeOffset, long>(
                    long (DateTimeOffset value) => value.UtcTicks,
                    DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<DateTimeOffset, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<DateTimeOffset, long>(
                        long (DateTimeOffset value) => value.UtcTicks,
                        DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero))));
            receivedAt.SetSentinelFromProviderValue(0L);

            var unknownChannelIds = runtimeEntityType.AddProperty(
                "UnknownChannelIds",
                typeof(byte[]),
                propertyInfo: typeof(PeerStorageRetrievalEntity).GetProperty("UnknownChannelIds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PeerStorageRetrievalEntity).GetField("<UnknownChannelIds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            unknownChannelIds.SetGetter(
                byte[] (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(instance),
                bool (PeerStorageRetrievalEntity instance) => PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(instance) == null);
            unknownChannelIds.SetSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, byte[] value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(instance) = value;
                    return instance;
                });
            unknownChannelIds.SetMaterializationSetter(
                PeerStorageRetrievalEntity (PeerStorageRetrievalEntity instance, byte[] value) =>
                {
                    PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(instance) = value;
                    return instance;
                });
            unknownChannelIds.SetAccessors(
                byte[] (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(((PeerStorageRetrievalEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => PeerStorageRetrievalEntityUnsafeAccessors.UnknownChannelIds(((PeerStorageRetrievalEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(unknownChannelIds, 4),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(unknownChannelIds));
            unknownChannelIds.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            unknownChannelIds.TypeMapping = SqliteByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()));

            var key = runtimeEntityType.AddKey(
                new[] { nodeId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var nodeId = runtimeEntityType.FindProperty("NodeId");
            var blob = runtimeEntityType.FindProperty("Blob");
            var matchesLastSent = runtimeEntityType.FindProperty("MatchesLastSent");
            var receivedAt = runtimeEntityType.FindProperty("ReceivedAt");
            var unknownChannelIds = runtimeEntityType.FindProperty("UnknownChannelIds");
            var key = runtimeEntityType.FindKey(new[] { nodeId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<CompactPubKey>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<CompactPubKey>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType1 = ((PeerStorageRetrievalEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<CompactPubKey, byte[], bool?, DateTimeOffset, byte[]>(((ValueComparer<CompactPubKey>)(((IProperty)nodeId).GetValueComparer())).Snapshot(source.GetCurrentValue<CompactPubKey>(nodeId)), (source.GetCurrentValue<byte[]>(blob) == null ? null : ((ValueComparer<byte[]>)(((IProperty)blob).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(blob))), (source.GetCurrentValue<bool?>(matchesLastSent) == null ? null : ((ValueComparer<bool?>)(((IProperty)matchesLastSent).GetValueComparer())).Snapshot(source.GetCurrentValue<bool?>(matchesLastSent))), ((ValueComparer<DateTimeOffset>)(((IProperty)receivedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(receivedAt)), (source.GetCurrentValue<byte[]>(unknownChannelIds) == null ? null : ((ValueComparer<byte[]>)(((IProperty)unknownChannelIds).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(unknownChannelIds))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType1 = ((PeerStorageRetrievalEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<CompactPubKey>(((ValueComparer<CompactPubKey>)(((IProperty)nodeId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<CompactPubKey>(nodeId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PeerStorageRetrievals");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
