<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release;Debug.Native;Release.Native</Configurations>
    <OutputType>Exe</OutputType>
    <Version>0.0.1</Version>
    <Description>Standalone local IPC signer daemon for NLightning.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <ProjectReference Include="..\NLightning.Infrastructure.RemoteSigning\NLightning.Infrastructure.RemoteSigning.csproj"/>
    <ProjectReference Include="..\NLightning.Infrastructure.Repositories\NLightning.Infrastructure.Repositories.csproj"/>
  </ItemGroup>
</Project>
