namespace NLightning.Daemon.Handlers;

using Domain.Client.Constants;
using Domain.Client.Enums;
using Domain.Client.Exceptions;
using Domain.Client.Requests;
using Domain.Client.Responses;
using Domain.Payments.Interfaces;
using Interfaces;

/// <summary>
/// Creates and persists a hold invoice for a caller-supplied payment hash (ClientCommand 49, NL-995) through
/// <see cref="IInvoiceService"/>. The preimage is never generated by us: whoever settles later proves it by hash.
/// </summary>
public sealed class CreateHoldInvoiceClientHandler
    : IClientCommandHandler<CreateHoldInvoiceClientRequest, HoldInvoiceClientResponse>
{
    private readonly IInvoiceService _invoiceService;
    private readonly TimeProvider _timeProvider;

    /// <inheritdoc/>
    public ClientCommand Command => ClientCommand.CreateHoldInvoice;

    public CreateHoldInvoiceClientHandler(IInvoiceService invoiceService, TimeProvider timeProvider)
    {
        _invoiceService = invoiceService;
        _timeProvider = timeProvider;
    }

    /// <inheritdoc/>
    /// <exception cref="ClientException">The payment hash is missing, the amount is zero, the expiry is zero, or the
    /// invoice service rejected the arguments (<see cref="ErrorCodes.InvalidOperation"/>).</exception>
    public async Task<HoldInvoiceClientResponse> HandleAsync(CreateHoldInvoiceClientRequest request,
                                                             CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.PaymentHash == default)
            throw new ClientException(ErrorCodes.InvalidOperation, "The payment hash is missing.");
        if (request.Amount is { IsZero: true })
            throw new ClientException(ErrorCodes.InvalidOperation,
                                      "The invoice amount must be positive; leave it out for an any-amount invoice.");
        if (request.ExpirySeconds == 0)
            throw new ClientException(ErrorCodes.InvalidOperation, "The invoice expiry must be positive.");
        var labels = SourceLabelsGuard.Check(request.Label, request.Tags);

        try
        {
            var invoice = await _invoiceService.CreateHoldInvoiceAsync(request.PaymentHash, request.Amount,
                                                                       request.Description ?? string.Empty,
                                                                       request.ExpirySeconds, null, labels, ct);
            return new HoldInvoiceClientResponse(
                InvoiceInfoClientResponse.FromModel(invoice, _timeProvider.GetUtcNow()));
        }
        catch (ArgumentException e)
        {
            throw new ClientException(ErrorCodes.InvalidOperation, $"Invalid hold invoice: {e.Message}", e);
        }
    }
}

/// <summary>
/// Settles a held invoice with the preimage from outside (ClientCommand 50, NL-995) through
/// <see cref="IHoldInvoiceService"/>: the invoice settles in one save and every held part is fulfilled with it.
/// </summary>
public sealed class SettleHoldInvoiceClientHandler
    : IClientCommandHandler<SettleHoldInvoiceClientRequest, HoldInvoiceClientResponse>
{
    private readonly IHoldInvoiceService _holdInvoiceService;
    private readonly TimeProvider _timeProvider;

    /// <inheritdoc/>
    public ClientCommand Command => ClientCommand.SettleHoldInvoice;

    public SettleHoldInvoiceClientHandler(IHoldInvoiceService holdInvoiceService, TimeProvider timeProvider)
    {
        _holdInvoiceService = holdInvoiceService;
        _timeProvider = timeProvider;
    }

    /// <inheritdoc/>
    /// <exception cref="ClientException">The payment hash or preimage is missing, no invoice exists for the hash, the
    /// preimage does not hash to it, or the invoice is not <c>Held</c> anymore
    /// (<see cref="ErrorCodes.InvalidOperation"/>).</exception>
    public async Task<HoldInvoiceClientResponse> HandleAsync(SettleHoldInvoiceClientRequest request,
                                                             CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.PaymentHash == default)
            throw new ClientException(ErrorCodes.InvalidOperation, "The payment hash is missing.");
        if (request.Preimage == default)
            throw new ClientException(ErrorCodes.InvalidOperation, "The preimage is missing.");

        try
        {
            var invoice = await _holdInvoiceService.SettleHoldInvoiceAsync(request.PaymentHash, request.Preimage, ct);
            return new HoldInvoiceClientResponse(
                InvoiceInfoClientResponse.FromModel(invoice, _timeProvider.GetUtcNow()));
        }
        catch (ArgumentException e)
        {
            throw new ClientException(ErrorCodes.InvalidOperation, $"Invalid settle: {e.Message}", e);
        }
        catch (InvalidOperationException e) when (e.GetType() == typeof(InvalidOperationException))
        {
            // The contract's "not Held (anymore)" refusal, as for payinvoice's duplicate-hash one
            throw new ClientException(ErrorCodes.InvalidOperation, e.Message, e);
        }
    }
}

/// <summary>
/// Cancels a hold invoice (ClientCommand 51, NL-995) through <see cref="IHoldInvoiceService"/>: a held set's parts are
/// failed back with <c>incorrect_or_unknown_payment_details</c> and the row is <c>Canceled</c>; an open one is simply
/// canceled.
/// </summary>
public sealed class CancelHoldInvoiceClientHandler
    : IClientCommandHandler<CancelHoldInvoiceClientRequest, HoldInvoiceClientResponse>
{
    private readonly IHoldInvoiceService _holdInvoiceService;
    private readonly TimeProvider _timeProvider;

    /// <inheritdoc/>
    public ClientCommand Command => ClientCommand.CancelHoldInvoice;

    public CancelHoldInvoiceClientHandler(IHoldInvoiceService holdInvoiceService, TimeProvider timeProvider)
    {
        _holdInvoiceService = holdInvoiceService;
        _timeProvider = timeProvider;
    }

    /// <inheritdoc/>
    /// <exception cref="ClientException">The payment hash is missing, no invoice exists for it, or the invoice can no
    /// longer be canceled (<see cref="ErrorCodes.InvalidOperation"/>).</exception>
    public async Task<HoldInvoiceClientResponse> HandleAsync(CancelHoldInvoiceClientRequest request,
                                                             CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.PaymentHash == default)
            throw new ClientException(ErrorCodes.InvalidOperation, "The payment hash is missing.");

        try
        {
            var invoice = await _holdInvoiceService.CancelHoldInvoiceAsync(request.PaymentHash, ct);
            return new HoldInvoiceClientResponse(
                InvoiceInfoClientResponse.FromModel(invoice, _timeProvider.GetUtcNow()));
        }
        catch (ArgumentException e)
        {
            throw new ClientException(ErrorCodes.InvalidOperation, $"Invalid cancel: {e.Message}", e);
        }
        catch (InvalidOperationException e) when (e.GetType() == typeof(InvalidOperationException))
        {
            // The contract's "no longer open or held" refusal, as for payinvoice's duplicate-hash one
            throw new ClientException(ErrorCodes.InvalidOperation, e.Message, e);
        }
    }
}