// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using NLightning.Domain.Crypto.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Bitcoin;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    public static class BlockchainStateEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(BlockchainStateEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastProcessedAt>k__BackingField")]
        public static extern ref DateTime LastProcessedAt(BlockchainStateEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastProcessedBlockHash>k__BackingField")]
        public static extern ref Hash LastProcessedBlockHash(BlockchainStateEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastProcessedHeight>k__BackingField")]
        public static extern ref uint LastProcessedHeight(BlockchainStateEntity @this);
    }
}