// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Domain.Channels.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Channel;
using NLightning.Infrastructure.Persistence.ValueConverters;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class ChannelSignerGuardEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Channel.ChannelSignerGuardEntity",
                typeof(ChannelSignerGuardEntity),
                baseEntityType,
                propertyCount: 6,
                keyCount: 1);

            var channelId = runtimeEntityType.AddProperty(
                "ChannelId",
                typeof(ChannelId),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("ChannelId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<ChannelId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new ChannelIdConverter());
            channelId.SetGetter(
                ChannelId (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.ChannelId(instance),
                bool (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.ChannelId(instance).Equals(default(ChannelId)));
            channelId.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, ChannelId value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.ChannelId(instance) = value;
                    return instance;
                });
            channelId.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, ChannelId value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.ChannelId(instance) = value;
                    return instance;
                });
            channelId.SetAccessors(
                ChannelId (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.ChannelId(((ChannelSignerGuardEntity)(entry.Entity))),
                ChannelId (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.ChannelId(((ChannelSignerGuardEntity)(entry.Entity))),
                ChannelId (IInternalEntry entry) => entry.ReadOriginalValue<ChannelId>(channelId, 0),
                ChannelId (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<ChannelId>(channelId, 0));
            channelId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            channelId.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<ChannelId>(
                    bool (ChannelId v1, ChannelId v2) => v1.Equals(v2),
                    int (ChannelId v) => ((object)v).GetHashCode(),
                    ChannelId (ChannelId v) => v),
                keyComparer: new ValueComparer<ChannelId>(
                    bool (ChannelId v1, ChannelId v2) => v1.Equals(v2),
                    int (ChannelId v) => ((object)v).GetHashCode(),
                    ChannelId (ChannelId v) => v),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                converter: new ValueConverter<ChannelId, byte[]>(
                    byte[] (ChannelId channelId) => ((byte[])channelId),
                    ChannelId (byte[] bytes) => ((ChannelId)bytes)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ChannelId, byte[]>(
                    JsonByteArrayReaderWriter.Instance,
                    new ValueConverter<ChannelId, byte[]>(
                        byte[] (ChannelId channelId) => ((byte[])channelId),
                        ChannelId (byte[] bytes) => ((ChannelId)bytes))));
            channelId.SetCurrentValueComparer(new StructuralEntryCurrentProviderValueComparer(channelId));
            channelId.SetSentinelFromProviderValue(null);
            channelId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            channelId.AddAnnotation("Relational:ColumnName", "channel_id");

            var broadcastSignedCommitmentNumber = runtimeEntityType.AddProperty(
                "BroadcastSignedCommitmentNumber",
                typeof(long?),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("BroadcastSignedCommitmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<BroadcastSignedCommitmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            broadcastSignedCommitmentNumber.SetGetter(
                long? (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(instance),
                bool (ChannelSignerGuardEntity instance) => !(ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(instance).HasValue));
            broadcastSignedCommitmentNumber.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(instance) = value;
                    return instance;
                });
            broadcastSignedCommitmentNumber.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(instance) = value;
                    return instance;
                });
            broadcastSignedCommitmentNumber.SetAccessors(
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.BroadcastSignedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => entry.ReadOriginalValue<long?>(broadcastSignedCommitmentNumber, 1),
                long? (IInternalEntry entry) => entry.GetCurrentValue<long?>(broadcastSignedCommitmentNumber));
            broadcastSignedCommitmentNumber.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            broadcastSignedCommitmentNumber.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            broadcastSignedCommitmentNumber.SetComparer(new NullableValueComparer<long>(broadcastSignedCommitmentNumber.TypeMapping.Comparer));
            broadcastSignedCommitmentNumber.SetKeyComparer(new NullableValueComparer<long>(broadcastSignedCommitmentNumber.TypeMapping.KeyComparer));
            broadcastSignedCommitmentNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            broadcastSignedCommitmentNumber.AddAnnotation("Relational:ColumnName", "broadcast_signed_commitment_number");

            var dataLossDetected = runtimeEntityType.AddProperty(
                "DataLossDetected",
                typeof(bool),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("DataLossDetected", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<DataLossDetected>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            dataLossDetected.SetGetter(
                bool (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(instance),
                bool (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(instance) == false);
            dataLossDetected.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, bool value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(instance) = value;
                    return instance;
                });
            dataLossDetected.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, bool value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(instance) = value;
                    return instance;
                });
            dataLossDetected.SetAccessors(
                bool (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(((ChannelSignerGuardEntity)(entry.Entity))),
                bool (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.DataLossDetected(((ChannelSignerGuardEntity)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(dataLossDetected, 2),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(dataLossDetected));
            dataLossDetected.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            dataLossDetected.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            dataLossDetected.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            dataLossDetected.AddAnnotation("Relational:ColumnName", "data_loss_detected");

            var localCommitmentNumber = runtimeEntityType.AddProperty(
                "LocalCommitmentNumber",
                typeof(long),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("LocalCommitmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<LocalCommitmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            localCommitmentNumber.SetGetter(
                long (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(instance),
                bool (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(instance) == 0L);
            localCommitmentNumber.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(instance) = value;
                    return instance;
                });
            localCommitmentNumber.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(instance) = value;
                    return instance;
                });
            localCommitmentNumber.SetAccessors(
                long (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.LocalCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(localCommitmentNumber, 3),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(localCommitmentNumber));
            localCommitmentNumber.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            localCommitmentNumber.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            localCommitmentNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            localCommitmentNumber.AddAnnotation("Relational:ColumnName", "local_commitment_number");

            var remoteSignedCommitmentNumber = runtimeEntityType.AddProperty(
                "RemoteSignedCommitmentNumber",
                typeof(long?),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("RemoteSignedCommitmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<RemoteSignedCommitmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            remoteSignedCommitmentNumber.SetGetter(
                long? (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(instance),
                bool (ChannelSignerGuardEntity instance) => !(ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(instance).HasValue));
            remoteSignedCommitmentNumber.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(instance) = value;
                    return instance;
                });
            remoteSignedCommitmentNumber.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(instance) = value;
                    return instance;
                });
            remoteSignedCommitmentNumber.SetAccessors(
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.RemoteSignedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => entry.ReadOriginalValue<long?>(remoteSignedCommitmentNumber, 4),
                long? (IInternalEntry entry) => entry.GetCurrentValue<long?>(remoteSignedCommitmentNumber));
            remoteSignedCommitmentNumber.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            remoteSignedCommitmentNumber.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            remoteSignedCommitmentNumber.SetComparer(new NullableValueComparer<long>(remoteSignedCommitmentNumber.TypeMapping.Comparer));
            remoteSignedCommitmentNumber.SetKeyComparer(new NullableValueComparer<long>(remoteSignedCommitmentNumber.TypeMapping.KeyComparer));
            remoteSignedCommitmentNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            remoteSignedCommitmentNumber.AddAnnotation("Relational:ColumnName", "remote_signed_commitment_number");

            var revokedCommitmentNumber = runtimeEntityType.AddProperty(
                "RevokedCommitmentNumber",
                typeof(long?),
                propertyInfo: typeof(ChannelSignerGuardEntity).GetProperty("RevokedCommitmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChannelSignerGuardEntity).GetField("<RevokedCommitmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            revokedCommitmentNumber.SetGetter(
                long? (ChannelSignerGuardEntity instance) => ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(instance),
                bool (ChannelSignerGuardEntity instance) => !(ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(instance).HasValue));
            revokedCommitmentNumber.SetSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(instance) = value;
                    return instance;
                });
            revokedCommitmentNumber.SetMaterializationSetter(
                ChannelSignerGuardEntity (ChannelSignerGuardEntity instance, long? value) =>
                {
                    ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(instance) = value;
                    return instance;
                });
            revokedCommitmentNumber.SetAccessors(
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => ChannelSignerGuardEntityUnsafeAccessors.RevokedCommitmentNumber(((ChannelSignerGuardEntity)(entry.Entity))),
                long? (IInternalEntry entry) => entry.ReadOriginalValue<long?>(revokedCommitmentNumber, 5),
                long? (IInternalEntry entry) => entry.GetCurrentValue<long?>(revokedCommitmentNumber));
            revokedCommitmentNumber.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            revokedCommitmentNumber.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            revokedCommitmentNumber.SetComparer(new NullableValueComparer<long>(revokedCommitmentNumber.TypeMapping.Comparer));
            revokedCommitmentNumber.SetKeyComparer(new NullableValueComparer<long>(revokedCommitmentNumber.TypeMapping.KeyComparer));
            revokedCommitmentNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            revokedCommitmentNumber.AddAnnotation("Relational:ColumnName", "revoked_commitment_number");

            var key = runtimeEntityType.AddKey(
                new[] { channelId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_channel_signer_guards");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var channelId = runtimeEntityType.FindProperty("ChannelId");
            var broadcastSignedCommitmentNumber = runtimeEntityType.FindProperty("BroadcastSignedCommitmentNumber");
            var dataLossDetected = runtimeEntityType.FindProperty("DataLossDetected");
            var localCommitmentNumber = runtimeEntityType.FindProperty("LocalCommitmentNumber");
            var remoteSignedCommitmentNumber = runtimeEntityType.FindProperty("RemoteSignedCommitmentNumber");
            var revokedCommitmentNumber = runtimeEntityType.FindProperty("RevokedCommitmentNumber");
            var key = runtimeEntityType.FindKey(new[] { channelId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<ChannelId>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<ChannelId>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType1 = ((ChannelSignerGuardEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<ChannelId, long?, bool, long, long?, long?>(((ValueComparer<ChannelId>)(((IProperty)channelId).GetValueComparer())).Snapshot(source.GetCurrentValue<ChannelId>(channelId)), (source.GetCurrentValue<long?>(broadcastSignedCommitmentNumber) == null ? null : ((ValueComparer<long?>)(((IProperty)broadcastSignedCommitmentNumber).GetValueComparer())).Snapshot(source.GetCurrentValue<long?>(broadcastSignedCommitmentNumber))), ((ValueComparer<bool>)(((IProperty)dataLossDetected).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(dataLossDetected)), ((ValueComparer<long>)(((IProperty)localCommitmentNumber).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(localCommitmentNumber)), (source.GetCurrentValue<long?>(remoteSignedCommitmentNumber) == null ? null : ((ValueComparer<long?>)(((IProperty)remoteSignedCommitmentNumber).GetValueComparer())).Snapshot(source.GetCurrentValue<long?>(remoteSignedCommitmentNumber))), (source.GetCurrentValue<long?>(revokedCommitmentNumber) == null ? null : ((ValueComparer<long?>)(((IProperty)revokedCommitmentNumber).GetValueComparer())).Snapshot(source.GetCurrentValue<long?>(revokedCommitmentNumber))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType1 = ((ChannelSignerGuardEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<ChannelId>(((ValueComparer<ChannelId>)(((IProperty)channelId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<ChannelId>(channelId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "channel_signer_guards");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}