// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using NLightning.Infrastructure.Persistence.Entities.Node;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class NodeSigningEnrollmentEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Node.NodeSigningEnrollmentEntity",
                typeof(NodeSigningEnrollmentEntity),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.Id(instance),
                bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, int value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, int value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.Id(((NodeSigningEnrollmentEntity)(entry.Entity))),
                int (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.Id(((NodeSigningEnrollmentEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var createdAtTicks = runtimeEntityType.AddProperty(
                "CreatedAtTicks",
                typeof(long),
                propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("CreatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<CreatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            createdAtTicks.SetGetter(
                long (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(instance),
                bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(instance) == 0L);
            createdAtTicks.SetSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, long value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetMaterializationSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, long value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetAccessors(
                long (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(((NodeSigningEnrollmentEntity)(entry.Entity))),
                long (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.CreatedAtTicks(((NodeSigningEnrollmentEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(createdAtTicks, 1),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(createdAtTicks));
            createdAtTicks.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            createdAtTicks.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAtTicks.AddAnnotation("Relational:ColumnName", "created_at_ticks");

            var network = runtimeEntityType.AddProperty(
                "Network",
                typeof(string),
                propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("Network", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<Network>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            network.SetGetter(
                string (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.Network(instance),
                bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.Network(instance) == null);
            network.SetSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.Network(instance) = value;
                    return instance;
                });
            network.SetMaterializationSetter(
                NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
                {
                    NodeSigningEnrollmentEntityUnsafeAccessors.Network(instance) = value;
                    return instance;
                });
            network.SetAccessors(
                string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.Network(((NodeSigningEnrollmentEntity)(entry.Entity))),
                string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.Network(((NodeSigningEnrollmentEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(network, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(network));
            network.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            network.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(64)",
                    size: 64));
            network.TypeMapping = ((NpgsqlStringTypeMapping)network.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        network.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        network.AddAnnotation("Relational:ColumnName", "network");

        var nodeId = runtimeEntityType.AddProperty(
            "NodeId",
            typeof(string),
            propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("NodeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<NodeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 128);
        nodeId.SetGetter(
            string (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(instance),
            bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(instance) == null);
        nodeId.SetSetter(
            NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
            {
                NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(instance) = value;
                return instance;
            });
        nodeId.SetMaterializationSetter(
            NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
            {
                NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(instance) = value;
                return instance;
            });
        nodeId.SetAccessors(
            string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(((NodeSigningEnrollmentEntity)(entry.Entity))),
            string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.NodeId(((NodeSigningEnrollmentEntity)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(nodeId, 3),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(nodeId));
        nodeId.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        nodeId.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(128)",
                size: 128));
        nodeId.TypeMapping = ((NpgsqlStringTypeMapping)nodeId.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    nodeId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
    nodeId.AddAnnotation("Relational:ColumnName", "node_id");

    var nodePublicKey = runtimeEntityType.AddProperty(
        "NodePublicKey",
        typeof(byte[]),
        propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("NodePublicKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<NodePublicKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 33);
    nodePublicKey.SetGetter(
        byte[] (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(instance),
        bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(instance) == null);
    nodePublicKey.SetSetter(
        NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, byte[] value) =>
        {
            NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(instance) = value;
            return instance;
        });
    nodePublicKey.SetMaterializationSetter(
        NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, byte[] value) =>
        {
            NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(instance) = value;
            return instance;
        });
    nodePublicKey.SetAccessors(
        byte[] (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(((NodeSigningEnrollmentEntity)(entry.Entity))),
        byte[] (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.NodePublicKey(((NodeSigningEnrollmentEntity)(entry.Entity))),
        byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(nodePublicKey, 4),
        byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(nodePublicKey));
    nodePublicKey.SetPropertyIndexes(
        index: 4,
        originalValueIndex: 4,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    nodePublicKey.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
        comparer: new ValueComparer<byte[]>(
            bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
            int (byte[] v) => ((object)v).GetHashCode(),
            byte[] (byte[] v) => v),
        keyComparer: new ValueComparer<byte[]>(
            bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
            int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
            byte[] (byte[] source) => source.ToArray()),
        providerValueComparer: new ValueComparer<byte[]>(
            bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
            int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
            byte[] (byte[] source) => source.ToArray()),
        mappingInfo: new RelationalTypeMappingInfo(
            size: 33));
    nodePublicKey.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
    nodePublicKey.AddAnnotation("Relational:ColumnName", "node_public_key");

    var ownerId = runtimeEntityType.AddProperty(
        "OwnerId",
        typeof(string),
        propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("OwnerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<OwnerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 128);
    ownerId.SetGetter(
        string (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(instance),
        bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(instance) == null);
    ownerId.SetSetter(
        NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
        {
            NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(instance) = value;
            return instance;
        });
    ownerId.SetMaterializationSetter(
        NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
        {
            NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(instance) = value;
            return instance;
        });
    ownerId.SetAccessors(
        string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(((NodeSigningEnrollmentEntity)(entry.Entity))),
        string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.OwnerId(((NodeSigningEnrollmentEntity)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(ownerId, 5),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(ownerId));
    ownerId.SetPropertyIndexes(
        index: 5,
        originalValueIndex: 5,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    ownerId.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(128)",
            size: 128));
    ownerId.TypeMapping = ((NpgsqlStringTypeMapping)ownerId.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
ownerId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
ownerId.AddAnnotation("Relational:ColumnName", "owner_id");

var schemaVersion = runtimeEntityType.AddProperty(
    "SchemaVersion",
    typeof(int),
    propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("SchemaVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<SchemaVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0);
schemaVersion.SetGetter(
    int (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(instance),
    bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(instance) == 0);
schemaVersion.SetSetter(
    NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, int value) =>
    {
        NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(instance) = value;
        return instance;
    });
schemaVersion.SetMaterializationSetter(
    NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, int value) =>
    {
        NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(instance) = value;
        return instance;
    });
schemaVersion.SetAccessors(
    int (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(((NodeSigningEnrollmentEntity)(entry.Entity))),
    int (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.SchemaVersion(((NodeSigningEnrollmentEntity)(entry.Entity))),
    int (IInternalEntry entry) => entry.ReadOriginalValue<int>(schemaVersion, 6),
    int (IInternalEntry entry) => entry.GetCurrentValue<int>(schemaVersion));
schemaVersion.SetPropertyIndexes(
    index: 6,
    originalValueIndex: 6,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
schemaVersion.TypeMapping = IntTypeMapping.Default.Clone(
    comparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    keyComparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    providerValueComparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "integer"));
schemaVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
schemaVersion.AddAnnotation("Relational:ColumnName", "schema_version");

var signerId = runtimeEntityType.AddProperty(
    "SignerId",
    typeof(string),
    propertyInfo: typeof(NodeSigningEnrollmentEntity).GetProperty("SignerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(NodeSigningEnrollmentEntity).GetField("<SignerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 128);
signerId.SetGetter(
    string (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(instance),
    bool (NodeSigningEnrollmentEntity instance) => NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(instance) == null);
signerId.SetSetter(
    NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
    {
        NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(instance) = value;
        return instance;
    });
signerId.SetMaterializationSetter(
    NodeSigningEnrollmentEntity (NodeSigningEnrollmentEntity instance, string value) =>
    {
        NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(instance) = value;
        return instance;
    });
signerId.SetAccessors(
    string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(((NodeSigningEnrollmentEntity)(entry.Entity))),
    string (IInternalEntry entry) => NodeSigningEnrollmentEntityUnsafeAccessors.SignerId(((NodeSigningEnrollmentEntity)(entry.Entity))),
    string (IInternalEntry entry) => entry.ReadOriginalValue<string>(signerId, 7),
    string (IInternalEntry entry) => entry.GetCurrentValue<string>(signerId));
signerId.SetPropertyIndexes(
    index: 7,
    originalValueIndex: 7,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
signerId.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    keyComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(128)",
        size: 128));
signerId.TypeMapping = ((NpgsqlStringTypeMapping)signerId.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
signerId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
signerId.AddAnnotation("Relational:ColumnName", "signer_id");

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);
key.AddAnnotation("Relational:Name", "pk_node_signing_enrollments");

return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var createdAtTicks = runtimeEntityType.FindProperty("CreatedAtTicks");
    var network = runtimeEntityType.FindProperty("Network");
    var nodeId = runtimeEntityType.FindProperty("NodeId");
    var nodePublicKey = runtimeEntityType.FindProperty("NodePublicKey");
    var ownerId = runtimeEntityType.FindProperty("OwnerId");
    var schemaVersion = runtimeEntityType.FindProperty("SchemaVersion");
    var signerId = runtimeEntityType.FindProperty("SignerId");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType1 = ((NodeSigningEnrollmentEntity)(source.Entity));
            return ((ISnapshot)(new Snapshot<int, long, string, string, byte[], string, int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<long>)(((IProperty)createdAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(createdAtTicks)), (source.GetCurrentValue<string>(network) == null ? null : ((ValueComparer<string>)(((IProperty)network).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(network))), (source.GetCurrentValue<string>(nodeId) == null ? null : ((ValueComparer<string>)(((IProperty)nodeId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(nodeId))), (source.GetCurrentValue<byte[]>(nodePublicKey) == null ? null : ((ValueComparer<byte[]>)(((IProperty)nodePublicKey).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(nodePublicKey))), (source.GetCurrentValue<string>(ownerId) == null ? null : ((ValueComparer<string>)(((IProperty)ownerId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ownerId))), ((ValueComparer<int>)(((IProperty)schemaVersion).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(schemaVersion)), (source.GetCurrentValue<string>(signerId) == null ? null : ((ValueComparer<string>)(((IProperty)signerId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(signerId))))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => Snapshot.Empty);
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType1 = ((NodeSigningEnrollmentEntity)(source.Entity));
            return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 8,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 8,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 0));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "node_signing_enrollments");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}