// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using NLightning.Domain.Channels.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Channel;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    public static class RemoteShachainEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref ChannelId ChannelId(RemoteShachainEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bucket>k__BackingField")]
        public static extern ref byte Bucket(RemoteShachainEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Index>k__BackingField")]
        public static extern ref long Index(RemoteShachainEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Secret>k__BackingField")]
        public static extern ref byte[] Secret(RemoteShachainEntity @this);
    }
}