// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Infrastructure.Persistence.Entities.Bitcoin;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class WalletHistoryRescanStateEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletHistoryRescanStateEntity",
                typeof(WalletHistoryRescanStateEntity),
                baseEntityType,
                propertyCount: 11,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Id(instance),
                bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, int value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, int value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Id(((WalletHistoryRescanStateEntity)(entry.Entity))),
                int (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Id(((WalletHistoryRescanStateEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var addressCount = runtimeEntityType.AddProperty(
                "AddressCount",
                typeof(uint),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("AddressCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<AddressCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            addressCount.SetGetter(
                uint (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(instance),
                bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(instance) == 0U);
            addressCount.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(instance) = value;
                    return instance;
                });
            addressCount.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(instance) = value;
                    return instance;
                });
            addressCount.SetAccessors(
                uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.AddressCount(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(addressCount, 1),
                uint (IInternalEntry entry) => entry.GetCurrentValue<uint>(addressCount));
            addressCount.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            addressCount.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                converter: new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<uint, long>(
                        long (uint v) => ((long)v),
                        uint (long v) => ((uint)v))));
            addressCount.SetSentinelFromProviderValue(0L);
            addressCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            addressCount.AddAnnotation("Relational:ColumnName", "address_count");

            var availableFromHeight = runtimeEntityType.AddProperty(
                "AvailableFromHeight",
                typeof(uint),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("AvailableFromHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<AvailableFromHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            availableFromHeight.SetGetter(
                uint (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(instance),
                bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(instance) == 0U);
            availableFromHeight.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(instance) = value;
                    return instance;
                });
            availableFromHeight.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(instance) = value;
                    return instance;
                });
            availableFromHeight.SetAccessors(
                uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.AvailableFromHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(availableFromHeight, 2),
                uint (IInternalEntry entry) => entry.GetCurrentValue<uint>(availableFromHeight));
            availableFromHeight.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            availableFromHeight.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                converter: new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<uint, long>(
                        long (uint v) => ((long)v),
                        uint (long v) => ((uint)v))));
            availableFromHeight.SetSentinelFromProviderValue(0L);
            availableFromHeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            availableFromHeight.AddAnnotation("Relational:ColumnName", "available_from_height");

            var cursorHash = runtimeEntityType.AddProperty(
                "CursorHash",
                typeof(byte[]),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("CursorHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<CursorHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 32);
            cursorHash.SetGetter(
                byte[] (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(instance),
                bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(instance) == null);
            cursorHash.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, byte[] value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(instance) = value;
                    return instance;
                });
            cursorHash.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, byte[] value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(instance) = value;
                    return instance;
                });
            cursorHash.SetAccessors(
                byte[] (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(((WalletHistoryRescanStateEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHash(((WalletHistoryRescanStateEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(cursorHash, 3),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(cursorHash));
            cursorHash.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            cursorHash.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                mappingInfo: new RelationalTypeMappingInfo(
                    size: 32));
            cursorHash.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            cursorHash.AddAnnotation("Relational:ColumnName", "cursor_hash");

            var cursorHeight = runtimeEntityType.AddProperty(
                "CursorHeight",
                typeof(uint?),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("CursorHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<CursorHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            cursorHeight.SetGetter(
                uint? (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(instance),
                bool (WalletHistoryRescanStateEntity instance) => !(WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(instance).HasValue));
            cursorHeight.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint? value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(instance) = value;
                    return instance;
                });
            cursorHeight.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint? value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(instance) = value;
                    return instance;
                });
            cursorHeight.SetAccessors(
                uint? (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint? (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.CursorHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
                uint? (IInternalEntry entry) => entry.ReadOriginalValue<uint?>(cursorHeight, 4),
                uint? (IInternalEntry entry) => entry.GetCurrentValue<uint?>(cursorHeight));
            cursorHeight.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            cursorHeight.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                converter: new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<uint, long>(
                        long (uint v) => ((long)v),
                        uint (long v) => ((uint)v))));
            cursorHeight.SetComparer(new NullableValueComparer<uint>(cursorHeight.TypeMapping.Comparer));
            cursorHeight.SetKeyComparer(new NullableValueComparer<uint>(cursorHeight.TypeMapping.KeyComparer));
            cursorHeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            cursorHeight.AddAnnotation("Relational:ColumnName", "cursor_height");

            var error = runtimeEntityType.AddProperty(
                "Error",
                typeof(string),
                propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("Error", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<Error>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1024);
            error.SetGetter(
                string (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Error(instance),
                bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Error(instance) == null);
            error.SetSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, string value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.Error(instance) = value;
                    return instance;
                });
            error.SetMaterializationSetter(
                WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, string value) =>
                {
                    WalletHistoryRescanStateEntityUnsafeAccessors.Error(instance) = value;
                    return instance;
                });
            error.SetAccessors(
                string (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Error(((WalletHistoryRescanStateEntity)(entry.Entity))),
                string (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Error(((WalletHistoryRescanStateEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(error, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(error));
            error.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            error.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(1024)",
                    size: 1024));
            error.TypeMapping = ((NpgsqlStringTypeMapping)error.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        error.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        error.AddAnnotation("Relational:ColumnName", "error");

        var generation = runtimeEntityType.AddProperty(
            "Generation",
            typeof(Guid),
            propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("Generation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<Generation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
        generation.SetGetter(
            Guid (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Generation(instance),
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.Generation(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
        generation.SetSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, Guid value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.Generation(instance) = value;
                return instance;
            });
        generation.SetMaterializationSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, Guid value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.Generation(instance) = value;
                return instance;
            });
        generation.SetAccessors(
            Guid (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Generation(((WalletHistoryRescanStateEntity)(entry.Entity))),
            Guid (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.Generation(((WalletHistoryRescanStateEntity)(entry.Entity))),
            Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(generation, 6),
            Guid (IInternalEntry entry) => entry.GetCurrentValue<Guid>(generation));
        generation.SetPropertyIndexes(
            index: 6,
            originalValueIndex: 6,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        generation.TypeMapping = GuidTypeMapping.Default.Clone(
            comparer: new ValueComparer<Guid>(
                bool (Guid v1, Guid v2) => v1 == v2,
                int (Guid v) => ((object)v).GetHashCode(),
                Guid (Guid v) => v),
            keyComparer: new ValueComparer<Guid>(
                bool (Guid v1, Guid v2) => v1 == v2,
                int (Guid v) => ((object)v).GetHashCode(),
                Guid (Guid v) => v),
            providerValueComparer: new ValueComparer<Guid>(
                bool (Guid v1, Guid v2) => v1 == v2,
                int (Guid v) => ((object)v).GetHashCode(),
                Guid (Guid v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "uuid"));
        generation.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        generation.AddAnnotation("Relational:ColumnName", "generation");

        var isActive = runtimeEntityType.AddProperty(
            "IsActive",
            typeof(bool),
            propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: false);
        isActive.SetGetter(
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(instance),
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(instance) == false);
        isActive.SetSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, bool value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetMaterializationSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, bool value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetAccessors(
            bool (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(((WalletHistoryRescanStateEntity)(entry.Entity))),
            bool (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.IsActive(((WalletHistoryRescanStateEntity)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 7),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
        isActive.SetPropertyIndexes(
            index: 7,
            originalValueIndex: 7,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        isActive.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
            comparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            keyComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            providerValueComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v));
        isActive.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        isActive.AddAnnotation("Relational:ColumnName", "is_active");

        var isPartial = runtimeEntityType.AddProperty(
            "IsPartial",
            typeof(bool),
            propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("IsPartial", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<IsPartial>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: false);
        isPartial.SetGetter(
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(instance),
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(instance) == false);
        isPartial.SetSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, bool value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(instance) = value;
                return instance;
            });
        isPartial.SetMaterializationSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, bool value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(instance) = value;
                return instance;
            });
        isPartial.SetAccessors(
            bool (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(((WalletHistoryRescanStateEntity)(entry.Entity))),
            bool (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.IsPartial(((WalletHistoryRescanStateEntity)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isPartial, 8),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isPartial));
        isPartial.SetPropertyIndexes(
            index: 8,
            originalValueIndex: 8,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        isPartial.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
            comparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            keyComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            providerValueComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v));
        isPartial.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        isPartial.AddAnnotation("Relational:ColumnName", "is_partial");

        var requestedFromHeight = runtimeEntityType.AddProperty(
            "RequestedFromHeight",
            typeof(uint),
            propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("RequestedFromHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<RequestedFromHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
        requestedFromHeight.SetGetter(
            uint (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(instance),
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(instance) == 0U);
        requestedFromHeight.SetSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(instance) = value;
                return instance;
            });
        requestedFromHeight.SetMaterializationSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(instance) = value;
                return instance;
            });
        requestedFromHeight.SetAccessors(
            uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
            uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.RequestedFromHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
            uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(requestedFromHeight, 9),
            uint (IInternalEntry entry) => entry.GetCurrentValue<uint>(requestedFromHeight));
        requestedFromHeight.SetPropertyIndexes(
            index: 9,
            originalValueIndex: 9,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        requestedFromHeight.TypeMapping = LongTypeMapping.Default.Clone(
            comparer: new ValueComparer<uint>(
                bool (uint v1, uint v2) => v1 == v2,
                int (uint v) => ((int)v),
                uint (uint v) => v),
            keyComparer: new ValueComparer<uint>(
                bool (uint v1, uint v2) => v1 == v2,
                int (uint v) => ((int)v),
                uint (uint v) => v),
            providerValueComparer: new ValueComparer<long>(
                bool (long v1, long v2) => v1 == v2,
                int (long v) => ((object)v).GetHashCode(),
                long (long v) => v),
            converter: new ValueConverter<uint, long>(
                long (uint v) => ((long)v),
                uint (long v) => ((uint)v)),
            jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                JsonInt64ReaderWriter.Instance,
                new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v))));
        requestedFromHeight.SetSentinelFromProviderValue(0L);
        requestedFromHeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        requestedFromHeight.AddAnnotation("Relational:ColumnName", "requested_from_height");

        var targetHeight = runtimeEntityType.AddProperty(
            "TargetHeight",
            typeof(uint),
            propertyInfo: typeof(WalletHistoryRescanStateEntity).GetProperty("TargetHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(WalletHistoryRescanStateEntity).GetField("<TargetHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
        targetHeight.SetGetter(
            uint (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(instance),
            bool (WalletHistoryRescanStateEntity instance) => WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(instance) == 0U);
        targetHeight.SetSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(instance) = value;
                return instance;
            });
        targetHeight.SetMaterializationSetter(
            WalletHistoryRescanStateEntity (WalletHistoryRescanStateEntity instance, uint value) =>
            {
                WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(instance) = value;
                return instance;
            });
        targetHeight.SetAccessors(
            uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
            uint (IInternalEntry entry) => WalletHistoryRescanStateEntityUnsafeAccessors.TargetHeight(((WalletHistoryRescanStateEntity)(entry.Entity))),
            uint (IInternalEntry entry) => entry.ReadOriginalValue<uint>(targetHeight, 10),
            uint (IInternalEntry entry) => entry.GetCurrentValue<uint>(targetHeight));
        targetHeight.SetPropertyIndexes(
            index: 10,
            originalValueIndex: 10,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        targetHeight.TypeMapping = LongTypeMapping.Default.Clone(
            comparer: new ValueComparer<uint>(
                bool (uint v1, uint v2) => v1 == v2,
                int (uint v) => ((int)v),
                uint (uint v) => v),
            keyComparer: new ValueComparer<uint>(
                bool (uint v1, uint v2) => v1 == v2,
                int (uint v) => ((int)v),
                uint (uint v) => v),
            providerValueComparer: new ValueComparer<long>(
                bool (long v1, long v2) => v1 == v2,
                int (long v) => ((object)v).GetHashCode(),
                long (long v) => v),
            converter: new ValueConverter<uint, long>(
                long (uint v) => ((long)v),
                uint (long v) => ((uint)v)),
            jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                JsonInt64ReaderWriter.Instance,
                new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v))));
        targetHeight.SetSentinelFromProviderValue(0L);
        targetHeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        targetHeight.AddAnnotation("Relational:ColumnName", "target_height");

        var key = runtimeEntityType.AddKey(
            new[] { id });
        runtimeEntityType.SetPrimaryKey(key);
        key.AddAnnotation("Relational:Name", "pk_wallet_history_rescan_states");

        return runtimeEntityType;
    }

    public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
    {
        var id = runtimeEntityType.FindProperty("Id");
        var addressCount = runtimeEntityType.FindProperty("AddressCount");
        var availableFromHeight = runtimeEntityType.FindProperty("AvailableFromHeight");
        var cursorHash = runtimeEntityType.FindProperty("CursorHash");
        var cursorHeight = runtimeEntityType.FindProperty("CursorHeight");
        var error = runtimeEntityType.FindProperty("Error");
        var generation = runtimeEntityType.FindProperty("Generation");
        var isActive = runtimeEntityType.FindProperty("IsActive");
        var isPartial = runtimeEntityType.FindProperty("IsPartial");
        var requestedFromHeight = runtimeEntityType.FindProperty("RequestedFromHeight");
        var targetHeight = runtimeEntityType.FindProperty("TargetHeight");
        var key = runtimeEntityType.FindKey(new[] { id });
        key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
        key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
        runtimeEntityType.SetOriginalValuesFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((WalletHistoryRescanStateEntity)(source.Entity));
                return ((ISnapshot)(new Snapshot<int, uint, uint, byte[], uint?, string, Guid, bool, bool, uint, uint>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<uint>)(((IProperty)addressCount).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(addressCount)), ((ValueComparer<uint>)(((IProperty)availableFromHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(availableFromHeight)), (source.GetCurrentValue<byte[]>(cursorHash) == null ? null : ((ValueComparer<byte[]>)(((IProperty)cursorHash).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(cursorHash))), (source.GetCurrentValue<uint?>(cursorHeight) == null ? null : ((ValueComparer<uint?>)(((IProperty)cursorHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint?>(cursorHeight))), (source.GetCurrentValue<string>(error) == null ? null : ((ValueComparer<string>)(((IProperty)error).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(error))), ((ValueComparer<Guid>)(((IProperty)generation).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(generation)), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), ((ValueComparer<bool>)(((IProperty)isPartial).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isPartial)), ((ValueComparer<uint>)(((IProperty)requestedFromHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(requestedFromHeight)), ((ValueComparer<uint>)(((IProperty)targetHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(targetHeight)))));
            });
        runtimeEntityType.SetStoreGeneratedValuesFactory(
            ISnapshot () => Snapshot.Empty);
        runtimeEntityType.SetTemporaryValuesFactory(
            ISnapshot (IInternalEntry source) => Snapshot.Empty);
        runtimeEntityType.SetShadowValuesFactory(
            ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
        runtimeEntityType.SetEmptyShadowValuesFactory(
            ISnapshot () => Snapshot.Empty);
        runtimeEntityType.SetRelationshipSnapshotFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((WalletHistoryRescanStateEntity)(source.Entity));
                return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
            });
        runtimeEntityType.SetCounts(new PropertyCounts(
            propertyCount: 11,
            navigationCount: 0,
            complexPropertyCount: 0,
            complexCollectionCount: 0,
            originalValueCount: 11,
            shadowCount: 0,
            relationshipCount: 1,
            storeGeneratedCount: 0));
        runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
        runtimeEntityType.AddAnnotation("Relational:Schema", null);
        runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
        runtimeEntityType.AddAnnotation("Relational:TableName", "wallet_history_rescan_states");
        runtimeEntityType.AddAnnotation("Relational:ViewName", null);
        runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

        Customize(runtimeEntityType);
    }

    static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}