// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Domain.Bitcoin.ValueObjects;
using NLightning.Infrastructure.Persistence.Entities.Bitcoin;
using NLightning.Infrastructure.Persistence.ValueConverters;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NLightning.Infrastructure.Persistence.CompiledModels.Postgres
{
    [EntityFrameworkInternal]
    public partial class WalletTransactionEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletTransactionEntity",
                typeof(WalletTransactionEntity),
                baseEntityType,
                propertyCount: 8,
                unnamedIndexCount: 1,
                keyCount: 1);

            var transactionId = runtimeEntityType.AddProperty(
                "TransactionId",
                typeof(TxId),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("TransactionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<TransactionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TxIdConverter());
            transactionId.SetGetter(
                TxId (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.TransactionId(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.TransactionId(instance).Equals(default(TxId)));
            transactionId.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, TxId value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.TransactionId(instance) = value;
                    return instance;
                });
            transactionId.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, TxId value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.TransactionId(instance) = value;
                    return instance;
                });
            transactionId.SetAccessors(
                TxId (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.TransactionId(((WalletTransactionEntity)(entry.Entity))),
                TxId (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.TransactionId(((WalletTransactionEntity)(entry.Entity))),
                TxId (IInternalEntry entry) => entry.ReadOriginalValue<TxId>(transactionId, 0),
                TxId (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<TxId>(transactionId, 0));
            transactionId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            transactionId.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<TxId>(
                    bool (TxId v1, TxId v2) => v1.Equals(v2),
                    int (TxId v) => ((object)v).GetHashCode(),
                    TxId (TxId v) => v),
                keyComparer: new ValueComparer<TxId>(
                    bool (TxId v1, TxId v2) => v1.Equals(v2),
                    int (TxId v) => ((object)v).GetHashCode(),
                    TxId (TxId v) => v),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                converter: new ValueConverter<TxId, byte[]>(
                    byte[] (TxId txId) => ((byte[])txId),
                    TxId (byte[] bytes) => new TxId(bytes)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<TxId, byte[]>(
                    JsonByteArrayReaderWriter.Instance,
                    new ValueConverter<TxId, byte[]>(
                        byte[] (TxId txId) => ((byte[])txId),
                        TxId (byte[] bytes) => new TxId(bytes))));
            transactionId.SetCurrentValueComparer(new StructuralEntryCurrentProviderValueComparer(transactionId));
            transactionId.SetSentinelFromProviderValue(null);
            transactionId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            transactionId.AddAnnotation("Relational:ColumnName", "transaction_id");

            var blockHash = runtimeEntityType.AddProperty(
                "BlockHash",
                typeof(byte[]),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("BlockHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<BlockHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 32);
            blockHash.SetGetter(
                byte[] (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.BlockHash(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.BlockHash(instance) == null);
            blockHash.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, byte[] value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.BlockHash(instance) = value;
                    return instance;
                });
            blockHash.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, byte[] value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.BlockHash(instance) = value;
                    return instance;
                });
            blockHash.SetAccessors(
                byte[] (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.BlockHash(((WalletTransactionEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.BlockHash(((WalletTransactionEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(blockHash, 1),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(blockHash));
            blockHash.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            blockHash.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                mappingInfo: new RelationalTypeMappingInfo(
                    size: 32));
            blockHash.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            blockHash.AddAnnotation("Relational:ColumnName", "block_hash");

            var blockHeight = runtimeEntityType.AddProperty(
                "BlockHeight",
                typeof(uint?),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("BlockHeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<BlockHeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            blockHeight.SetGetter(
                uint? (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.BlockHeight(instance),
                bool (WalletTransactionEntity instance) => !(WalletTransactionEntityUnsafeAccessors.BlockHeight(instance).HasValue));
            blockHeight.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, uint? value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.BlockHeight(instance) = value;
                    return instance;
                });
            blockHeight.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, uint? value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.BlockHeight(instance) = value;
                    return instance;
                });
            blockHeight.SetAccessors(
                uint? (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.BlockHeight(((WalletTransactionEntity)(entry.Entity))),
                uint? (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.BlockHeight(((WalletTransactionEntity)(entry.Entity))),
                uint? (IInternalEntry entry) => entry.ReadOriginalValue<uint?>(blockHeight, 2),
                uint? (IInternalEntry entry) => entry.GetCurrentValue<uint?>(blockHeight));
            blockHeight.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            blockHeight.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)v),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                converter: new ValueConverter<uint, long>(
                    long (uint v) => ((long)v),
                    uint (long v) => ((uint)v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<uint, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<uint, long>(
                        long (uint v) => ((long)v),
                        uint (long v) => ((uint)v))));
            blockHeight.SetComparer(new NullableValueComparer<uint>(blockHeight.TypeMapping.Comparer));
            blockHeight.SetKeyComparer(new NullableValueComparer<uint>(blockHeight.TypeMapping.KeyComparer));
            blockHeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            blockHeight.AddAnnotation("Relational:ColumnName", "block_height");

            var ourInputs = runtimeEntityType.AddProperty(
                "OurInputs",
                typeof(string),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("OurInputs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<OurInputs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ourInputs.SetGetter(
                string (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OurInputs(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OurInputs(instance) == null);
            ourInputs.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OurInputs(instance) = value;
                    return instance;
                });
            ourInputs.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OurInputs(instance) = value;
                    return instance;
                });
            ourInputs.SetAccessors(
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OurInputs(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OurInputs(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(ourInputs, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(ourInputs));
            ourInputs.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ourInputs.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            ourInputs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            ourInputs.AddAnnotation("Relational:ColumnName", "our_inputs");

            var ourOutputs = runtimeEntityType.AddProperty(
                "OurOutputs",
                typeof(string),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("OurOutputs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<OurOutputs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ourOutputs.SetGetter(
                string (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OurOutputs(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OurOutputs(instance) == null);
            ourOutputs.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OurOutputs(instance) = value;
                    return instance;
                });
            ourOutputs.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OurOutputs(instance) = value;
                    return instance;
                });
            ourOutputs.SetAccessors(
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OurOutputs(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OurOutputs(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(ourOutputs, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(ourOutputs));
            ourOutputs.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ourOutputs.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            ourOutputs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            ourOutputs.AddAnnotation("Relational:ColumnName", "our_outputs");

            var ownershipSummary = runtimeEntityType.AddProperty(
                "OwnershipSummary",
                typeof(string),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("OwnershipSummary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<OwnershipSummary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ownershipSummary.SetGetter(
                string (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OwnershipSummary(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.OwnershipSummary(instance) == null);
            ownershipSummary.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OwnershipSummary(instance) = value;
                    return instance;
                });
            ownershipSummary.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, string value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.OwnershipSummary(instance) = value;
                    return instance;
                });
            ownershipSummary.SetAccessors(
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OwnershipSummary(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.OwnershipSummary(((WalletTransactionEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(ownershipSummary, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(ownershipSummary));
            ownershipSummary.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ownershipSummary.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            ownershipSummary.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            ownershipSummary.AddAnnotation("Relational:ColumnName", "ownership_summary");

            var rawTransaction = runtimeEntityType.AddProperty(
                "RawTransaction",
                typeof(byte[]),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("RawTransaction", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<RawTransaction>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            rawTransaction.SetGetter(
                byte[] (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.RawTransaction(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.RawTransaction(instance) == null);
            rawTransaction.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, byte[] value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.RawTransaction(instance) = value;
                    return instance;
                });
            rawTransaction.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, byte[] value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.RawTransaction(instance) = value;
                    return instance;
                });
            rawTransaction.SetAccessors(
                byte[] (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.RawTransaction(((WalletTransactionEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.RawTransaction(((WalletTransactionEntity)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(rawTransaction, 6),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(rawTransaction));
            rawTransaction.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            rawTransaction.TypeMapping = NpgsqlByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()));
            rawTransaction.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            rawTransaction.AddAnnotation("Relational:ColumnName", "raw_transaction");

            var timestamp = runtimeEntityType.AddProperty(
                "Timestamp",
                typeof(DateTimeOffset),
                propertyInfo: typeof(WalletTransactionEntity).GetProperty("Timestamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WalletTransactionEntity).GetField("<Timestamp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcTicksConverter());
            timestamp.SetGetter(
                DateTimeOffset (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.Timestamp(instance),
                bool (WalletTransactionEntity instance) => WalletTransactionEntityUnsafeAccessors.Timestamp(instance).EqualsExact(default(DateTimeOffset)));
            timestamp.SetSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, DateTimeOffset value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.Timestamp(instance) = value;
                    return instance;
                });
            timestamp.SetMaterializationSetter(
                WalletTransactionEntity (WalletTransactionEntity instance, DateTimeOffset value) =>
                {
                    WalletTransactionEntityUnsafeAccessors.Timestamp(instance) = value;
                    return instance;
                });
            timestamp.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.Timestamp(((WalletTransactionEntity)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => WalletTransactionEntityUnsafeAccessors.Timestamp(((WalletTransactionEntity)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(timestamp, 7),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(timestamp));
            timestamp.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timestamp.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                keyComparer: new ValueComparer<DateTimeOffset>(
                    bool (DateTimeOffset v1, DateTimeOffset v2) => v1.EqualsExact(v2),
                    int (DateTimeOffset v) => ((object)v).GetHashCode(),
                    DateTimeOffset (DateTimeOffset v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                converter: new ValueConverter<DateTimeOffset, long>(
                    long (DateTimeOffset value) => value.UtcTicks,
                    DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<DateTimeOffset, long>(
                    JsonInt64ReaderWriter.Instance,
                    new ValueConverter<DateTimeOffset, long>(
                        long (DateTimeOffset value) => value.UtcTicks,
                        DateTimeOffset (long ticks) => new DateTimeOffset(ticks, TimeSpan.Zero))));
            timestamp.SetSentinelFromProviderValue(0L);
            timestamp.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timestamp.AddAnnotation("Relational:ColumnName", "timestamp");

            var key = runtimeEntityType.AddKey(
                new[] { transactionId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_wallet_transactions");

            var index = runtimeEntityType.AddIndex(
                new[] { blockHeight });
            index.AddAnnotation("Relational:Name", "ix_wallet_transactions_block_height");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var transactionId = runtimeEntityType.FindProperty("TransactionId");
            var blockHash = runtimeEntityType.FindProperty("BlockHash");
            var blockHeight = runtimeEntityType.FindProperty("BlockHeight");
            var ourInputs = runtimeEntityType.FindProperty("OurInputs");
            var ourOutputs = runtimeEntityType.FindProperty("OurOutputs");
            var ownershipSummary = runtimeEntityType.FindProperty("OwnershipSummary");
            var rawTransaction = runtimeEntityType.FindProperty("RawTransaction");
            var timestamp = runtimeEntityType.FindProperty("Timestamp");
            var key = runtimeEntityType.FindKey(new[] { transactionId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<TxId>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<TxId>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((WalletTransactionEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<TxId, byte[], uint?, string, string, string, byte[], DateTimeOffset>(((ValueComparer<TxId>)(((IProperty)transactionId).GetValueComparer())).Snapshot(source.GetCurrentValue<TxId>(transactionId)), (source.GetCurrentValue<byte[]>(blockHash) == null ? null : ((ValueComparer<byte[]>)(((IProperty)blockHash).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(blockHash))), (source.GetCurrentValue<uint?>(blockHeight) == null ? null : ((ValueComparer<uint?>)(((IProperty)blockHeight).GetValueComparer())).Snapshot(source.GetCurrentValue<uint?>(blockHeight))), (source.GetCurrentValue<string>(ourInputs) == null ? null : ((ValueComparer<string>)(((IProperty)ourInputs).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ourInputs))), (source.GetCurrentValue<string>(ourOutputs) == null ? null : ((ValueComparer<string>)(((IProperty)ourOutputs).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ourOutputs))), (source.GetCurrentValue<string>(ownershipSummary) == null ? null : ((ValueComparer<string>)(((IProperty)ownershipSummary).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ownershipSummary))), (source.GetCurrentValue<byte[]>(rawTransaction) == null ? null : ((ValueComparer<byte[]>)(((IProperty)rawTransaction).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(rawTransaction))), ((ValueComparer<DateTimeOffset>)(((IProperty)timestamp).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(timestamp)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((WalletTransactionEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<TxId>(((ValueComparer<TxId>)(((IProperty)transactionId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<TxId>(transactionId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "wallet_transactions");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}