name: 'Test Report'
on:
  workflow_run:
    workflows: ['NLightning .NET Build & Tests']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read 
  checks: write
  actions: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Process trx reports with default
        if: always()
        # You may also reference just the major or major.minor version
        uses: im-open/process-dotnet-test-results@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}