name: 'Test Report'
on:
  workflow_run:
    workflows: ['NLightning .NET Build & Tests']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read 
  checks: write
  actions: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: xUnit Tests            # Name of the check run which will be created
          path: coverage/test-results.trx   # Path to test results
          reporter: dotnet-trx        # Format of test results