<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <Deterministic>true</Deterministic>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release;Debug.Native;Release.Native</Configurations>
  </PropertyGroup>

  <!-- Check if this is being used in AOT projects -->
  <PropertyGroup Condition="'$(PublishAot)' == 'true' Or $(Configuration.Contains('.Native'))">
    <DefineConstants>CRYPTO_NATIVE;$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <!-- Check if this is being used in non-AOT and non-WASM projects -->
  <PropertyGroup Condition="'$(UsingMicrosoftNETSdkBlazorWebAssembly)' != 'true' And '$(PublishAot)' != 'true' And !$(Configuration.Contains('.Wasm')) And !$(Configuration.Contains('.Native'))">
    <DefineConstants>CRYPTO_LIBSODIUM;$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0"/>
    <PackageReference Include="Moq" Version="4.20.72"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NLightning.Domain\NLightning.Domain.csproj"/>
    <ProjectReference Include="..\..\src\NLightning.Infrastructure\NLightning.Infrastructure.csproj"/>
    <ProjectReference Include="..\NLightning.Tests.Utils\NLightning.Tests.Utils.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="Crypto\Vectors\SHA256LongMsg.rsp" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

</Project>
